//! Bit-identity tests vs the Python `jax_core` reference.
//!
//! `tests/fixtures/jax_core_reference.json` is generated by the
//! co-located `emit_jax_core_reference.py` script (running the v5 Python
//! `mpa_scale_solver.jax_core` primitives over a small input sweep).
//! Python is the canonical reference (per BLOCK_IN §v6 "Python is the
//! pseudo-code spec for v6"); these tests assert each Rust primitive in
//! `src/math.rs` reproduces the Python output within a per-primitive ULP
//! budget — the v6 acceptance "byte-identical for deterministic ops"
//! check, scoped to math.rs.
//!
//! Tolerance discipline (tiered per primitive per the user direction at
//! session start):
//!   - LIBM (4 ULPs): primitives composing a small number of libm calls
//!     (tangent_flow_*, banach_state, lookup_squared_distance,
//!     tangent_flow_canonical_inverse, laplace_covariance_*).
//!   - LIBM_WIDE (16 ULPs): primitives composing many libm calls and / or
//!     sums whose reduction order differs between JAX (pairwise) and Rust
//!     (sequential): caputo_flow, mlp_forward, learned_field_substrate,
//!     laplace_log_evidence.
//! No primitive currently qualifies as "pure arithmetic on every path"
//! (the v0 identity branches do, but they share a budget with their
//! libm-routing siblings).
//!
//! Regenerating the fixture: rerun `emit_jax_core_reference.py` and
//! commit the JSON diff. The test will catch unintended divergence on
//! the next `cargo test --release`.

use std::fs;
use std::path::PathBuf;

use std::collections::BTreeMap;

use mpa_scale_solver::flow::flow;
use mpa_scale_solver::gfdr_model::{
    EmpiricalRow, alpha_s, generate_locus, interp_locus, locus_residual, plateau_height,
    vertex_regime,
};
use mpa_scale_solver::math::{
    Activation, MlpLayer, banach_state, caputo_flow, laplace_covariance_from_hessian,
    laplace_covariance_from_jacobian, laplace_log_evidence, learned_field_substrate,
    lookup_squared_distance, mlp_forward, tangent_flow_canonical,
    tangent_flow_canonical_inverse, tangent_flow_inversion_residual, tangent_flow_substrate,
};
use mpa_scale_solver::sidecar::round_key;
use mpa_scale_solver::types::{
    CanonicalPoint, CanonicalState, Direction, Gt, OperatingPoint, RegimeLabel, ScalingRule,
    TangentFlowField, TranslationField, TranslationRule,
};
use serde_json::Value;

const LIBM: u64 = 4;
const LIBM_WIDE: u64 = 16;

// ---------------------------------------------------------------------------
// Fixture loading + JSON helpers
// ---------------------------------------------------------------------------

fn load_fixture() -> Value {
    let path =
        PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("tests/fixtures/jax_core_reference.json");
    let text = fs::read_to_string(&path)
        .unwrap_or_else(|e| panic!("could not read {}: {}", path.display(), e));
    serde_json::from_str(&text).expect("fixture JSON parse")
}

fn f(v: &Value) -> f64 {
    v.as_f64().expect("expected f64")
}
fn vec_f(v: &Value) -> Vec<f64> {
    v.as_array().expect("array").iter().map(f).collect()
}
fn vec_b(v: &Value) -> Vec<bool> {
    v.as_array()
        .expect("array")
        .iter()
        .map(|e| e.as_bool().expect("expected bool"))
        .collect()
}
fn mat_f(v: &Value) -> Vec<Vec<f64>> {
    v.as_array().expect("array").iter().map(vec_f).collect()
}

fn parse_layers(v: &Value) -> Vec<MlpLayer> {
    v.as_array()
        .expect("layers array")
        .iter()
        .map(|layer| MlpLayer {
            w: mat_f(&layer["w"]),
            b: vec_f(&layer["b"]),
        })
        .collect()
}

fn parse_activation(v: &Value) -> Activation {
    match v.as_str().expect("activation string") {
        "tanh" => Activation::Tanh,
        "relu" => Activation::Relu,
        other => panic!("unsupported activation: {other}"),
    }
}

// ---------------------------------------------------------------------------
// ULP comparison
// ---------------------------------------------------------------------------

/// Count ULPs between two f64 values. Returns `u64::MAX` for non-finite
/// or different-sign values (which always fail any finite tolerance).
fn ulps_between(a: f64, b: f64) -> u64 {
    if a == b {
        return 0;
    }
    if !a.is_finite() || !b.is_finite() {
        return u64::MAX;
    }
    if a.is_sign_negative() != b.is_sign_negative() {
        return u64::MAX;
    }
    a.to_bits().abs_diff(b.to_bits())
}

#[track_caller]
fn assert_close(actual: f64, expected: f64, tol_ulps: u64, label: &str) {
    if actual == expected {
        return;
    }
    let ulps = ulps_between(actual, expected);
    assert!(
        ulps <= tol_ulps,
        "{label}: actual={actual} expected={expected} differs by {ulps} ULPs (budget {tol_ulps})",
    );
}

// ---------------------------------------------------------------------------
// Fixture coverage guard — fails loudly if the emitter drops a primitive.
// ---------------------------------------------------------------------------

#[test]
fn fixture_covers_all_expected_primitives() {
    let fixture = load_fixture();
    let obj = fixture.as_object().expect("top-level object");
    let expected = [
        // session 2 — jax_core.py → math.rs (12 primitives)
        "tangent_flow_substrate",
        "banach_state",
        "tangent_flow_canonical",
        "lookup_squared_distance",
        "tangent_flow_canonical_inverse",
        "tangent_flow_inversion_residual",
        "laplace_covariance_from_jacobian",
        "laplace_covariance_from_hessian",
        "caputo_flow",
        "mlp_forward",
        "learned_field_substrate",
        "laplace_log_evidence",
        // session 4 — gfdr_model.py → gfdr_model.rs (6)
        "gfdr_alpha_s",
        "gfdr_plateau_height",
        "gfdr_vertex_regime",
        "gfdr_generate_locus",
        "gfdr_interp_locus",
        "gfdr_locus_residual",
        // session 4 — sidecar.py → sidecar.rs (1)
        "sidecar_round_key",
        // session 4 — flow.py → flow.rs (1)
        "flow",
    ];
    assert_eq!(
        obj.len(),
        expected.len(),
        "fixture has {} primitives, expected {}",
        obj.len(),
        expected.len()
    );
    for name in expected {
        assert!(obj.contains_key(name), "fixture missing primitive: {name}");
    }
}

// ---------------------------------------------------------------------------
// Per-primitive bit-identity tests
// ---------------------------------------------------------------------------

#[test]
fn jax_core_tangent_flow_substrate() {
    let fixture = load_fixture();
    for (i, case) in fixture["tangent_flow_substrate"]
        .as_array()
        .unwrap()
        .iter()
        .enumerate()
    {
        let inp = &case["inputs"];
        let exp = &case["outputs"];
        let (chit, gamma) = tangent_flow_substrate(
            f(&inp["chit"]),
            f(&inp["gamma_ab"]),
            f(&inp["delta_chit"]),
            f(&inp["delta_gamma"]),
            f(&inp["tau_obs"]),
            f(&inp["tau_obs_ref"]),
        );
        assert_close(
            chit,
            f(&exp["chit"]),
            LIBM,
            &format!("tangent_flow_substrate[{i}].chit"),
        );
        assert_close(
            gamma,
            f(&exp["gamma_ab"]),
            LIBM,
            &format!("tangent_flow_substrate[{i}].gamma_ab"),
        );
    }
}

#[test]
fn jax_core_banach_state() {
    let fixture = load_fixture();
    for (i, case) in fixture["banach_state"].as_array().unwrap().iter().enumerate() {
        let inp = &case["inputs"];
        let exp = &case["outputs"];
        let (chit, gamma) = banach_state(
            f(&inp["chit_0"]),
            f(&inp["gamma_ab_0"]),
            f(&inp["lambda_chit"]),
            f(&inp["lambda_gamma"]),
            f(&inp["nu"]),
        );
        assert_close(
            chit,
            f(&exp["chit"]),
            LIBM,
            &format!("banach_state[{i}].chit"),
        );
        assert_close(
            gamma,
            f(&exp["gamma_ab"]),
            LIBM,
            &format!("banach_state[{i}].gamma_ab"),
        );
    }
}

#[test]
fn jax_core_tangent_flow_canonical() {
    let fixture = load_fixture();
    for (i, case) in fixture["tangent_flow_canonical"]
        .as_array()
        .unwrap()
        .iter()
        .enumerate()
    {
        let inp = &case["inputs"];
        let exp = &case["outputs"];
        let (chit, gamma) = tangent_flow_canonical(
            f(&inp["chit_0"]),
            f(&inp["gamma_ab_0"]),
            f(&inp["delta_chit"]),
            f(&inp["delta_gamma"]),
            f(&inp["nu"]),
            f(&inp["tau_obs_ref"]),
        );
        assert_close(
            chit,
            f(&exp["chit"]),
            LIBM,
            &format!("tangent_flow_canonical[{i}].chit"),
        );
        assert_close(
            gamma,
            f(&exp["gamma_ab"]),
            LIBM,
            &format!("tangent_flow_canonical[{i}].gamma_ab"),
        );
    }
}

#[test]
fn jax_core_lookup_squared_distance() {
    let fixture = load_fixture();
    for (i, case) in fixture["lookup_squared_distance"]
        .as_array()
        .unwrap()
        .iter()
        .enumerate()
    {
        let inp = &case["inputs"];
        let exp = &case["outputs"];
        let chits = vec_f(&inp["field_chits"]);
        let gammas = vec_f(&inp["field_gammas"]);
        let taus = vec_f(&inp["field_taus"]);
        let has_tau = vec_b(&inp["has_tau"]);
        let d = lookup_squared_distance(
            f(&inp["query_chit"]),
            f(&inp["query_gamma"]),
            &chits,
            &gammas,
            &taus,
            &has_tau,
            f(&inp["tau_obs"]),
            f(&inp["tau_obs_weight"]),
        );
        let expected = vec_f(&exp["d2"]);
        assert_eq!(
            d.len(),
            expected.len(),
            "lookup_squared_distance[{i}] length mismatch"
        );
        for (k, (got, want)) in d.iter().zip(expected.iter()).enumerate() {
            assert_close(
                *got,
                *want,
                LIBM,
                &format!("lookup_squared_distance[{i}][{k}]"),
            );
        }
    }
}

#[test]
fn jax_core_tangent_flow_canonical_inverse() {
    let fixture = load_fixture();
    for (i, case) in fixture["tangent_flow_canonical_inverse"]
        .as_array()
        .unwrap()
        .iter()
        .enumerate()
    {
        let inp = &case["inputs"];
        let exp = &case["outputs"];
        let (chit, gamma) = tangent_flow_canonical_inverse(
            f(&inp["substrate_chit"]),
            f(&inp["substrate_gamma_ab"]),
            f(&inp["delta_chit"]),
            f(&inp["delta_gamma"]),
            f(&inp["tau_obs"]),
            f(&inp["tau_obs_ref"]),
        );
        assert_close(
            chit,
            f(&exp["chit"]),
            LIBM,
            &format!("tangent_flow_canonical_inverse[{i}].chit"),
        );
        assert_close(
            gamma,
            f(&exp["gamma_ab"]),
            LIBM,
            &format!("tangent_flow_canonical_inverse[{i}].gamma_ab"),
        );
    }
}

#[test]
fn jax_core_tangent_flow_inversion_residual() {
    let fixture = load_fixture();
    for (i, case) in fixture["tangent_flow_inversion_residual"]
        .as_array()
        .unwrap()
        .iter()
        .enumerate()
    {
        let inp = &case["inputs"];
        let exp = &case["outputs"];
        let r = tangent_flow_inversion_residual(
            f(&inp["candidate_chit"]),
            f(&inp["candidate_gamma"]),
            f(&inp["target_substrate_chit"]),
            f(&inp["target_substrate_gamma"]),
            f(&inp["delta_chit"]),
            f(&inp["delta_gamma"]),
            f(&inp["tau_obs"]),
            f(&inp["tau_obs_ref"]),
        );
        assert_close(
            r,
            f(&exp["residual"]),
            LIBM,
            &format!("tangent_flow_inversion_residual[{i}]"),
        );
    }
}

#[test]
fn jax_core_laplace_covariance_from_jacobian() {
    let fixture = load_fixture();
    for (i, case) in fixture["laplace_covariance_from_jacobian"]
        .as_array()
        .unwrap()
        .iter()
        .enumerate()
    {
        let inp = &case["inputs"];
        let exp = &case["outputs"];
        let j_rows = mat_f(&inp["jacobian"]);
        let j: Vec<[f64; 2]> = j_rows.iter().map(|row| [row[0], row[1]]).collect();
        let cov = laplace_covariance_from_jacobian(&j, f(&inp["noise_variance"]))
            .expect("non-singular");
        let expected = mat_f(&exp["covariance"]);
        for r in 0..2 {
            for c in 0..2 {
                assert_close(
                    cov[r][c],
                    expected[r][c],
                    LIBM,
                    &format!("laplace_covariance_from_jacobian[{i}][{r}][{c}]"),
                );
            }
        }
    }
}

#[test]
fn jax_core_laplace_covariance_from_hessian() {
    let fixture = load_fixture();
    for (i, case) in fixture["laplace_covariance_from_hessian"]
        .as_array()
        .unwrap()
        .iter()
        .enumerate()
    {
        let inp = &case["inputs"];
        let exp = &case["outputs"];
        let rows = mat_f(&inp["hessian"]);
        let h: [[f64; 2]; 2] = [[rows[0][0], rows[0][1]], [rows[1][0], rows[1][1]]];
        let cov = laplace_covariance_from_hessian(&h, f(&inp["noise_variance"]))
            .expect("non-singular");
        let expected = mat_f(&exp["covariance"]);
        for r in 0..2 {
            for c in 0..2 {
                assert_close(
                    cov[r][c],
                    expected[r][c],
                    LIBM,
                    &format!("laplace_covariance_from_hessian[{i}][{r}][{c}]"),
                );
            }
        }
    }
}

#[test]
fn jax_core_caputo_flow() {
    let fixture = load_fixture();
    for (i, case) in fixture["caputo_flow"].as_array().unwrap().iter().enumerate() {
        let inp = &case["inputs"];
        let exp = &case["outputs"];
        let amps = vec_f(&inp["prony_amplitudes"]);
        let decays = vec_f(&inp["prony_decays"]);
        let (chit, gamma) = caputo_flow(
            f(&inp["chit_0"]),
            f(&inp["gamma_ab_0"]),
            f(&inp["lambda_chit"]),
            f(&inp["lambda_gamma"]),
            f(&inp["nu"]),
            &amps,
            &decays,
        );
        assert_close(
            chit,
            f(&exp["chit"]),
            LIBM_WIDE,
            &format!("caputo_flow[{i}].chit"),
        );
        assert_close(
            gamma,
            f(&exp["gamma_ab"]),
            LIBM_WIDE,
            &format!("caputo_flow[{i}].gamma_ab"),
        );
    }
}

#[test]
fn jax_core_mlp_forward() {
    let fixture = load_fixture();
    for (i, case) in fixture["mlp_forward"].as_array().unwrap().iter().enumerate() {
        let inp = &case["inputs"];
        let exp = &case["outputs"];
        let x = vec_f(&inp["x"]);
        let layers = parse_layers(&inp["weights"]);
        let act = parse_activation(&inp["activation"]);
        let y = mlp_forward(&x, &layers, act);
        let expected = vec_f(&exp["y"]);
        assert_eq!(
            y.len(),
            expected.len(),
            "mlp_forward[{i}] length mismatch"
        );
        for (k, (got, want)) in y.iter().zip(expected.iter()).enumerate() {
            assert_close(*got, *want, LIBM_WIDE, &format!("mlp_forward[{i}][{k}]"));
        }
    }
}

#[test]
fn jax_core_learned_field_substrate() {
    let fixture = load_fixture();
    for (i, case) in fixture["learned_field_substrate"]
        .as_array()
        .unwrap()
        .iter()
        .enumerate()
    {
        let inp = &case["inputs"];
        let exp = &case["outputs"];
        let layers = parse_layers(&inp["weights"]);
        let act = parse_activation(&inp["activation"]);
        let (chit, gamma) = learned_field_substrate(
            f(&inp["chit"]),
            f(&inp["gamma_ab"]),
            f(&inp["tau_obs"]),
            f(&inp["tau_obs_ref"]),
            &layers,
            act,
        );
        assert_close(
            chit,
            f(&exp["chit"]),
            LIBM_WIDE,
            &format!("learned_field_substrate[{i}].chit"),
        );
        assert_close(
            gamma,
            f(&exp["gamma_ab"]),
            LIBM_WIDE,
            &format!("learned_field_substrate[{i}].gamma_ab"),
        );
    }
}

#[test]
fn jax_core_laplace_log_evidence() {
    let fixture = load_fixture();
    for (i, case) in fixture["laplace_log_evidence"]
        .as_array()
        .unwrap()
        .iter()
        .enumerate()
    {
        let inp = &case["inputs"];
        let exp = &case["outputs"];
        let rows = mat_f(&inp["hessian"]);
        let h: [[f64; 2]; 2] = [[rows[0][0], rows[0][1]], [rows[1][0], rows[1][1]]];
        let n_obs = inp["n_obs"].as_u64().expect("n_obs u64") as usize;
        let ev = laplace_log_evidence(
            f(&inp["residual_at_map"]),
            &h,
            f(&inp["noise_variance"]),
            n_obs,
        );
        assert_close(
            ev,
            f(&exp["log_evidence"]),
            LIBM_WIDE,
            &format!("laplace_log_evidence[{i}]"),
        );
    }
}

// ===========================================================================
// Session 4 — gfdr_model.rs primitives
// ===========================================================================

#[test]
fn gfdr_alpha_s_matches_python() {
    let fixture = load_fixture();
    for (i, case) in fixture["gfdr_alpha_s"].as_array().unwrap().iter().enumerate() {
        let chit = f(&case["inputs"]["chit"]);
        let expected = f(&case["outputs"]["alpha_s"]);
        assert_close(alpha_s(chit), expected, LIBM, &format!("alpha_s[{i}]"));
    }
}

#[test]
fn gfdr_plateau_height_matches_python() {
    let fixture = load_fixture();
    for (i, case) in fixture["gfdr_plateau_height"]
        .as_array()
        .unwrap()
        .iter()
        .enumerate()
    {
        let chit = f(&case["inputs"]["chit"]);
        let expected = f(&case["outputs"]["plateau_height"]);
        assert_close(
            plateau_height(chit),
            expected,
            LIBM,
            &format!("plateau_height[{i}]"),
        );
    }
}

#[test]
fn gfdr_vertex_regime_matches_python() {
    // String-equality test — no ULP budget needed.
    let fixture = load_fixture();
    for (i, case) in fixture["gfdr_vertex_regime"]
        .as_array()
        .unwrap()
        .iter()
        .enumerate()
    {
        let chit = f(&case["inputs"]["chit"]);
        // Python emits the regime as its `Literal` string; serde reads
        // it back into our enum via `rename_all = "snake_case"`.
        let want: RegimeLabel = serde_json::from_value(case["outputs"]["regime"].clone())
            .expect("regime string parses to enum");
        assert_eq!(
            vertex_regime(chit),
            want,
            "vertex_regime[{i}] chit={chit}"
        );
    }
}

#[test]
fn gfdr_generate_locus_matches_python() {
    let fixture = load_fixture();
    for (i, case) in fixture["gfdr_generate_locus"]
        .as_array()
        .unwrap()
        .iter()
        .enumerate()
    {
        let chit = f(&case["inputs"]["chit"]);
        let regime: RegimeLabel = serde_json::from_value(case["inputs"]["regime"].clone())
            .expect("regime parses");
        let locus = generate_locus(chit, regime);
        let want_tau = vec_f(&case["outputs"]["tau"]);
        let want_chi = vec_f(&case["outputs"]["chi"]);
        let want_c = vec_f(&case["outputs"]["C"]);
        assert_eq!(locus.len(), want_tau.len(), "generate_locus[{i}] length");
        for (k, p) in locus.iter().enumerate() {
            // `tau` is `tau_min * (tau_max/tau_min)^t` — same arithmetic
            // either side; LIBM budget covers libm-powf.
            assert_close(
                p.tau,
                want_tau[k],
                LIBM,
                &format!("generate_locus[{i}][{k}].tau"),
            );
            // `chi` and `C` compose exp / powf calls; the s-critical
            // branch sums two contributions → LIBM_WIDE.
            assert_close(
                p.chi,
                want_chi[k],
                LIBM_WIDE,
                &format!("generate_locus[{i}][{k}].chi"),
            );
            assert_close(
                p.c,
                want_c[k],
                LIBM_WIDE,
                &format!("generate_locus[{i}][{k}].C"),
            );
        }
    }
}

#[test]
fn gfdr_interp_locus_matches_python() {
    let fixture = load_fixture();
    for (i, case) in fixture["gfdr_interp_locus"]
        .as_array()
        .unwrap()
        .iter()
        .enumerate()
    {
        let chit = f(&case["inputs"]["chit"]);
        let tau = f(&case["inputs"]["tau"]);
        let regime = vertex_regime(chit);
        let locus = generate_locus(chit, regime);
        let (c, chi) = interp_locus(&locus, tau);
        assert_close(
            c,
            f(&case["outputs"]["C"]),
            LIBM,
            &format!("interp_locus[{i}].C"),
        );
        assert_close(
            chi,
            f(&case["outputs"]["chi"]),
            LIBM,
            &format!("interp_locus[{i}].chi"),
        );
    }
}

#[test]
fn gfdr_locus_residual_matches_python() {
    let fixture = load_fixture();
    for (i, case) in fixture["gfdr_locus_residual"]
        .as_array()
        .unwrap()
        .iter()
        .enumerate()
    {
        let candidate = f(&case["inputs"]["candidate_chit"]);
        let rows: Vec<EmpiricalRow> = case["inputs"]["empirical"]
            .as_array()
            .unwrap()
            .iter()
            .map(|row| EmpiricalRow {
                tau: f(&row["tau"]),
                chi: f(&row["chi"]),
                c: f(&row["C"]),
            })
            .collect();
        let r = locus_residual(&rows, candidate);
        // Five-term mean of squared diffs of `(C, chi)` against
        // interpolated locus values; cumulative reduction order matters.
        assert_close(
            r,
            f(&case["outputs"]["residual"]),
            LIBM_WIDE,
            &format!("locus_residual[{i}]"),
        );
    }
}

// ===========================================================================
// Session 4 — sidecar.rs cross-language rounding
// ===========================================================================

#[test]
fn sidecar_round_key_matches_python() {
    let fixture = load_fixture();
    for (i, case) in fixture["sidecar_round_key"]
        .as_array()
        .unwrap()
        .iter()
        .enumerate()
    {
        let chit = f(&case["inputs"]["chit"]);
        let gamma = f(&case["inputs"]["gamma_AB"]);
        let tau = f(&case["inputs"]["tau_obs"]);
        let decimals = case["inputs"]["decimals"].as_i64().unwrap() as i32;
        let (r_chit, r_gamma, r_tau) = round_key(chit, gamma, tau, decimals);
        // Python `round` and Rust `round_ties_even` can disagree by 1 ULP
        // at the rounded precision in pathological halfway cases; LIBM=4
        // covers everything the typical Banach-sidecar producer emits.
        assert_close(
            r_chit,
            f(&case["outputs"]["chit"]),
            LIBM,
            &format!("round_key[{i}].chit"),
        );
        assert_close(
            r_gamma,
            f(&case["outputs"]["gamma_AB"]),
            LIBM,
            &format!("round_key[{i}].gamma_AB"),
        );
        assert_close(
            r_tau,
            f(&case["outputs"]["tau_obs"]),
            LIBM,
            &format!("round_key[{i}].tau_obs"),
        );
    }
}

// ===========================================================================
// Session 4 — flow.rs dispatch (banach_exp / generic / Caputo)
// ===========================================================================

fn build_tangent_flow_field(inputs: &Value) -> TangentFlowField {
    let refinement: Option<BTreeMap<String, Value>> = match &inputs["refinement"] {
        Value::Null => None,
        Value::Object(map) => Some(map.iter().map(|(k, v)| (k.clone(), v.clone())).collect()),
        other => panic!("unexpected refinement shape: {other:?}"),
    };
    let origin = TranslationRule {
        operating_point: OperatingPoint {
            label: "origin".to_string(),
            gt: Gt::S,
            axes: BTreeMap::new(),
        },
        xdot_choice: "default".to_string(),
        canonical: CanonicalPoint {
            chit: 0.0,
            gamma_AB: 0.0,
            k_frust: false,
            method: "test".to_string(),
            extras: BTreeMap::new(),
        },
    };
    TangentFlowField {
        direction: Direction::Forward,
        rule_at_origin: origin,
        scaling: ScalingRule {
            tau_obs_ref: f(&inputs["tau_obs_ref"]),
            delta_chit: f(&inputs["delta_chit"]),
            delta_gamma: f(&inputs["delta_gamma"]),
            refinement,
        },
        description: None,
    }
}

#[test]
fn flow_matches_python_across_dispatch() {
    let fixture = load_fixture();
    for (i, case) in fixture["flow"].as_array().unwrap().iter().enumerate() {
        let inputs = &case["inputs"];
        let field = TranslationField::TangentFlow(build_tangent_flow_field(inputs));
        let initial = CanonicalState {
            chit: f(&inputs["chit_0"]),
            gamma_AB: f(&inputs["gamma_AB_0"]),
            k_frust: false,
        };
        let nu = f(&inputs["nu"]);
        let out = flow(&initial, nu, &field).expect("flow dispatch should succeed");
        // Branch budget: banach_exp / generic compose ≤ 2 libm calls per
        // axis (LIBM); Caputo sums prony_terms.len() exp() calls
        // sequentially (LIBM_WIDE for multi-term cases).
        let budget = if inputs["refinement"]["prony_terms"]
            .as_array()
            .map(|a| a.len() > 1)
            .unwrap_or(false)
        {
            LIBM_WIDE
        } else {
            LIBM
        };
        assert_close(
            out.chit,
            f(&case["outputs"]["chit"]),
            budget,
            &format!("flow[{i}].chit"),
        );
        assert_close(
            out.gamma_AB,
            f(&case["outputs"]["gamma_AB"]),
            budget,
            &format!("flow[{i}].gamma_AB"),
        );
    }
}
