//! Cross-language parity tests vs the Python reference.
//!
//! `tests/fixtures/jax_core_reference.json` is generated by the
//! co-located `emit_jax_core_reference.py` script (running the v5
//! Python reference over a small input sweep). Python is the
//! canonical reference (per BLOCK_IN §v6 "Python is the pseudo-code
//! spec for v6"); these tests assert that Rust agrees with Python
//! under contracts that vary by test category (see below).
//!
//! The file started life as math-primitive bit-identity (sessions 2,
//! 4) and grew through sessions 6–7 to host three additional
//! cross-language parity classes. Adding a new parity test? Pick the
//! category and follow its idiom.
//!
//! ## Test categories
//!
//! Four categories live here. Each new fixture entry + test should
//! pick one and follow its idiom — mixing categories on one entry
//! (e.g., putting a rational hash in a float field with ULP
//! tolerance) is the failure mode the fixture-discipline rule below
//! exists to prevent.
//!
//! 1. **Per-primitive bit-identity with ULP budgets** (sessions 2,
//!    4). One fixture entry per math primitive, each carrying a
//!    sweep of input cases. Rust runs the same primitive on each
//!    case and compares via `assert_close` with the per-primitive
//!    `LIBM` (4 ULPs) or `LIBM_WIDE` (16 ULPs) budget. Examples:
//!    `tangent_flow_substrate`, `banach_state`, `mlp_forward`,
//!    `caputo_flow`. **Use for: any new math.rs primitive.**
//!
//! 2. **Schema parity** (sessions 6, 7). One fixture entry per typed
//!    dataclass shape, each carrying a sweep of value cases. Rust
//!    deserializes via serde and asserts field-by-field equality —
//!    bit-exact on structured fields (enums, bools, integers),
//!    ULP-tolerant on computed floats per the discipline rule.
//!    Examples: `sacrifice_record` (session 6),
//!    `operation_output_regime_at` (session 7). **Use for: a new
//!    `OperationOutput<T>` wire-shape (`operation_output_posterior`
//!    is the planned session-8 instance), or any new
//!    Python-emitted-Rust-consumed typed dataclass.**
//!
//! 3. **Digest-bytes parity** (session 7). One fixture entry per
//!    rational / hash-derived value where the contract is exact-bit
//!    equality. Fixture stores raw bytes as hex; Rust computes the
//!    same digest and compares bytes directly — never goes through
//!    float. Example: `provenance_hash` (stores 4-byte blake2b
//!    digest as hex; compares via `provenance_digest_bytes`).
//!    **Use for: any new hash / fingerprint / rational-encoded
//!    artifact.**
//!
//! 4. **Wire-format parity** (session 7 followup). One fixture entry
//!    per full JSON-artifact contract. Python encodes a Python-native
//!    value via a spec-conformant serializer; Rust deserializes via
//!    serde and exercises consumer behavior end-to-end. Tests the
//!    cross-language contract as a whole, not individual fields.
//!    Example: `sidecar_wire_format` (encodes a Banach
//!    `InverseLookupSidecar` via `encode_sidecar_to_json`; Rust
//!    deserializes via `serde_json::from_str` and exercises both
//!    `lookup_forward` and `lookup_inverse` on every grid frame).
//!    **Use for: any new producer/consumer artifact with a
//!    spec doc** (currently: `docs/SIDECAR_FORMAT.md`).
//!
//! Regenerating the fixture: rerun `emit_jax_core_reference.py` and
//! commit the JSON diff. The coverage-guard test
//! (`fixture_covers_all_expected_primitives`) catches dropped
//! entries on the next `cargo test --release`.
//!
//! ## Fixture discipline — no bit-exact floats in JSON
//!
//! JSON stores floats as decimal strings, which cannot reliably
//! round-trip IEEE-754 doubles under naive parsers (serde_json's
//! default lazy parser can drop a ULP on some bit patterns). Two
//! rules follow:
//!
//! 1. **Computed floats** (residuals, drives, gamuts, MAP points,
//!    posterior moments — anything where the cross-language contract
//!    is "converges to the same value") use `assert_close` with a
//!    `LIBM` or `LIBM_WIDE` ULP budget. The budget absorbs both the
//!    wire-format drift and the libm reduction-order difference.
//!
//! 2. **Rational / digest values** (provenance_hash, sidecar keys,
//!    enum tags, integer counts — anything where the contract is
//!    "byte-identical") never go through `f64` in the fixture.
//!    Store the underlying bits as a hex string and compare bytes
//!    directly. Example: `provenance_digest_bytes` exposes the raw
//!    4-byte blake2b digest so the fixture stores `output_bits_hex`
//!    rather than the derived `n / 2^32` float.
//!
//! Adding `serde_json/float_roundtrip` to launder the rule is the
//! wrong direction: it papers over a fixture-design mistake at
//! ~50 KB wasm cost per consumer.
//!
//! ## The session-2 lesson (still load-bearing in sessions 4, 6, 7)
//!
//! Never generate `target = python_forward(candidate)` and ask Rust
//! to compute `residual = (rust_forward(candidate) - target)^2`.
//! libm cancellation makes Rust's residual ~1e-32 instead of
//! Python's exact 0, which fails any ULP tolerance even though no
//! port bug is present. Specify all paired `(candidate, target)`
//! inputs explicitly in the fixture so both implementations
//! evaluate the same numerical inputs. Documented at the
//! `gfdr_locus_residual` and `sidecar_round_key` case generators
//! in `emit_jax_core_reference.py`.

use std::fs;
use std::path::PathBuf;

use std::collections::BTreeMap;

use mpa_scale_solver::flow::flow;
use mpa_scale_solver::gfdr_model::{
    EmpiricalRow, alpha_s, generate_locus, interp_locus, locus_residual, plateau_height,
    vertex_regime,
};
use mpa_scale_solver::math::{
    Activation, MlpLayer, banach_state, caputo_flow, laplace_covariance_from_hessian,
    laplace_covariance_from_jacobian, laplace_log_evidence, learned_field_substrate,
    lookup_squared_distance, mlp_forward, tangent_flow_canonical,
    tangent_flow_canonical_inverse, tangent_flow_forward_jacobian,
    tangent_flow_inversion_residual, tangent_flow_substrate,
};
use mpa_scale_solver::operations::{
    forward_sweep_invert_posterior_wrapped, regime_at_wrapped,
};
use mpa_scale_solver::provenance::{make_provenance, provenance_digest_bytes, SOLVER_VERSION};
use mpa_scale_solver::sidecar::{lookup_forward, lookup_inverse, round_key, DEFAULT_ROUNDING_DECIMALS};
use mpa_scale_solver::types::{
    CanonicalPoint, CanonicalState, CapacityClass, Direction, DispatchPath, Gt, IntentDiagnostics,
    IntentId, InverseLookupSidecar, LookupTableField, OperatingPoint, RegimeLabel,
    SacrificeRecord, ScalingRule, SubstrateState, TangentFlowField, TranslationField,
    TranslationRule,
};
use serde_json::Value;

const LIBM: u64 = 4;
const LIBM_WIDE: u64 = 16;

// ---------------------------------------------------------------------------
// Fixture loading + JSON helpers
// ---------------------------------------------------------------------------

fn load_fixture() -> Value {
    let path =
        PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("tests/fixtures/jax_core_reference.json");
    let text = fs::read_to_string(&path)
        .unwrap_or_else(|e| panic!("could not read {}: {}", path.display(), e));
    serde_json::from_str(&text).expect("fixture JSON parse")
}

fn f(v: &Value) -> f64 {
    v.as_f64().expect("expected f64")
}
fn vec_f(v: &Value) -> Vec<f64> {
    v.as_array().expect("array").iter().map(f).collect()
}
fn vec_b(v: &Value) -> Vec<bool> {
    v.as_array()
        .expect("array")
        .iter()
        .map(|e| e.as_bool().expect("expected bool"))
        .collect()
}
fn mat_f(v: &Value) -> Vec<Vec<f64>> {
    v.as_array().expect("array").iter().map(vec_f).collect()
}

fn parse_layers(v: &Value) -> Vec<MlpLayer> {
    v.as_array()
        .expect("layers array")
        .iter()
        .map(|layer| MlpLayer {
            w: mat_f(&layer["w"]),
            b: vec_f(&layer["b"]),
        })
        .collect()
}

fn parse_activation(v: &Value) -> Activation {
    match v.as_str().expect("activation string") {
        "tanh" => Activation::Tanh,
        "relu" => Activation::Relu,
        other => panic!("unsupported activation: {other}"),
    }
}

// ---------------------------------------------------------------------------
// ULP comparison
// ---------------------------------------------------------------------------

/// Count ULPs between two f64 values. Returns `u64::MAX` for non-finite
/// or different-sign values (which always fail any finite tolerance).
fn ulps_between(a: f64, b: f64) -> u64 {
    if a == b {
        return 0;
    }
    if !a.is_finite() || !b.is_finite() {
        return u64::MAX;
    }
    if a.is_sign_negative() != b.is_sign_negative() {
        return u64::MAX;
    }
    a.to_bits().abs_diff(b.to_bits())
}

#[track_caller]
fn assert_close(actual: f64, expected: f64, tol_ulps: u64, label: &str) {
    if actual == expected {
        return;
    }
    let ulps = ulps_between(actual, expected);
    assert!(
        ulps <= tol_ulps,
        "{label}: actual={actual} expected={expected} differs by {ulps} ULPs (budget {tol_ulps})",
    );
}

// ---------------------------------------------------------------------------
// Fixture coverage guard — fails loudly if the emitter drops a primitive.
// ---------------------------------------------------------------------------

#[test]
fn fixture_covers_all_expected_primitives() {
    let fixture = load_fixture();
    let obj = fixture.as_object().expect("top-level object");
    let expected = [
        // session 2 — jax_core.py → math.rs (12 primitives)
        "tangent_flow_substrate",
        "banach_state",
        "tangent_flow_canonical",
        "lookup_squared_distance",
        "tangent_flow_canonical_inverse",
        "tangent_flow_inversion_residual",
        "laplace_covariance_from_jacobian",
        "laplace_covariance_from_hessian",
        "caputo_flow",
        "mlp_forward",
        "learned_field_substrate",
        "laplace_log_evidence",
        // session 4 — gfdr_model.py → gfdr_model.rs (6)
        "gfdr_alpha_s",
        "gfdr_plateau_height",
        "gfdr_vertex_regime",
        "gfdr_generate_locus",
        "gfdr_interp_locus",
        "gfdr_locus_residual",
        // session 4 — sidecar.py → sidecar.rs (1)
        "sidecar_round_key",
        // session 4 — flow.py → flow.rs (1)
        "flow",
        // session 6 — intent algebra (operations.py → operations.rs).
        // Schema parity, not bit-identity — see the dedicated test
        // below for the Python→Rust JSON parity contract.
        "sacrifice_record",
        // session 7 — provenance + wrapped-variant wire parity.
        // `provenance_hash` is bit-identity (4-byte blake2b digest must
        // match exactly); `operation_output_regime_at` is schema parity
        // (structured fields; timestamps + notes excluded — see the
        // section header in `emit_jax_core_reference.py` and the notes
        // asymmetry note in CLAUDE.md).
        "provenance_hash",
        "operation_output_regime_at",
        // session 7 followup — sidecar wire-format lock-in. Full JSON
        // round-trip parity per docs/SIDECAR_FORMAT.md v1.0.
        "sidecar_wire_format",
        // session 8 — posterior surface.
        // `tangent_flow_forward_jacobian` is per-primitive bit-identity
        // (category 1); the Rust port encodes the diagonal Jacobian
        // analytically while Python uses jax.jacfwd. Same single libm
        // pow call → LIBM tolerance.
        // `operation_output_posterior` is schema parity (category 2) for
        // the wrapped posterior variant — same template as session 7's
        // `operation_output_regime_at`, extended with the Posterior
        // value-struct contents (mean / covariance / log_evidence /
        // modes / notes).
        "tangent_flow_forward_jacobian",
        "operation_output_posterior",
    ];
    assert_eq!(
        obj.len(),
        expected.len(),
        "fixture has {} primitives, expected {}",
        obj.len(),
        expected.len()
    );
    for name in expected {
        assert!(obj.contains_key(name), "fixture missing primitive: {name}");
    }
}

// ---------------------------------------------------------------------------
// Per-primitive bit-identity tests
// ---------------------------------------------------------------------------

#[test]
fn jax_core_tangent_flow_substrate() {
    let fixture = load_fixture();
    for (i, case) in fixture["tangent_flow_substrate"]
        .as_array()
        .unwrap()
        .iter()
        .enumerate()
    {
        let inp = &case["inputs"];
        let exp = &case["outputs"];
        let (chit, gamma) = tangent_flow_substrate(
            f(&inp["chit"]),
            f(&inp["gamma_ab"]),
            f(&inp["delta_chit"]),
            f(&inp["delta_gamma"]),
            f(&inp["tau_obs"]),
            f(&inp["tau_obs_ref"]),
        );
        assert_close(
            chit,
            f(&exp["chit"]),
            LIBM,
            &format!("tangent_flow_substrate[{i}].chit"),
        );
        assert_close(
            gamma,
            f(&exp["gamma_ab"]),
            LIBM,
            &format!("tangent_flow_substrate[{i}].gamma_ab"),
        );
    }
}

#[test]
fn jax_core_banach_state() {
    let fixture = load_fixture();
    for (i, case) in fixture["banach_state"].as_array().unwrap().iter().enumerate() {
        let inp = &case["inputs"];
        let exp = &case["outputs"];
        let (chit, gamma) = banach_state(
            f(&inp["chit_0"]),
            f(&inp["gamma_ab_0"]),
            f(&inp["lambda_chit"]),
            f(&inp["lambda_gamma"]),
            f(&inp["nu"]),
        );
        assert_close(
            chit,
            f(&exp["chit"]),
            LIBM,
            &format!("banach_state[{i}].chit"),
        );
        assert_close(
            gamma,
            f(&exp["gamma_ab"]),
            LIBM,
            &format!("banach_state[{i}].gamma_ab"),
        );
    }
}

#[test]
fn jax_core_tangent_flow_canonical() {
    let fixture = load_fixture();
    for (i, case) in fixture["tangent_flow_canonical"]
        .as_array()
        .unwrap()
        .iter()
        .enumerate()
    {
        let inp = &case["inputs"];
        let exp = &case["outputs"];
        let (chit, gamma) = tangent_flow_canonical(
            f(&inp["chit_0"]),
            f(&inp["gamma_ab_0"]),
            f(&inp["delta_chit"]),
            f(&inp["delta_gamma"]),
            f(&inp["nu"]),
            f(&inp["tau_obs_ref"]),
        );
        assert_close(
            chit,
            f(&exp["chit"]),
            LIBM,
            &format!("tangent_flow_canonical[{i}].chit"),
        );
        assert_close(
            gamma,
            f(&exp["gamma_ab"]),
            LIBM,
            &format!("tangent_flow_canonical[{i}].gamma_ab"),
        );
    }
}

#[test]
fn jax_core_lookup_squared_distance() {
    let fixture = load_fixture();
    for (i, case) in fixture["lookup_squared_distance"]
        .as_array()
        .unwrap()
        .iter()
        .enumerate()
    {
        let inp = &case["inputs"];
        let exp = &case["outputs"];
        let chits = vec_f(&inp["field_chits"]);
        let gammas = vec_f(&inp["field_gammas"]);
        let taus = vec_f(&inp["field_taus"]);
        let has_tau = vec_b(&inp["has_tau"]);
        let d = lookup_squared_distance(
            f(&inp["query_chit"]),
            f(&inp["query_gamma"]),
            &chits,
            &gammas,
            &taus,
            &has_tau,
            f(&inp["tau_obs"]),
            f(&inp["tau_obs_weight"]),
        );
        let expected = vec_f(&exp["d2"]);
        assert_eq!(
            d.len(),
            expected.len(),
            "lookup_squared_distance[{i}] length mismatch"
        );
        for (k, (got, want)) in d.iter().zip(expected.iter()).enumerate() {
            assert_close(
                *got,
                *want,
                LIBM,
                &format!("lookup_squared_distance[{i}][{k}]"),
            );
        }
    }
}

#[test]
fn jax_core_tangent_flow_canonical_inverse() {
    let fixture = load_fixture();
    for (i, case) in fixture["tangent_flow_canonical_inverse"]
        .as_array()
        .unwrap()
        .iter()
        .enumerate()
    {
        let inp = &case["inputs"];
        let exp = &case["outputs"];
        let (chit, gamma) = tangent_flow_canonical_inverse(
            f(&inp["substrate_chit"]),
            f(&inp["substrate_gamma_ab"]),
            f(&inp["delta_chit"]),
            f(&inp["delta_gamma"]),
            f(&inp["tau_obs"]),
            f(&inp["tau_obs_ref"]),
        );
        assert_close(
            chit,
            f(&exp["chit"]),
            LIBM,
            &format!("tangent_flow_canonical_inverse[{i}].chit"),
        );
        assert_close(
            gamma,
            f(&exp["gamma_ab"]),
            LIBM,
            &format!("tangent_flow_canonical_inverse[{i}].gamma_ab"),
        );
    }
}

#[test]
fn jax_core_tangent_flow_inversion_residual() {
    let fixture = load_fixture();
    for (i, case) in fixture["tangent_flow_inversion_residual"]
        .as_array()
        .unwrap()
        .iter()
        .enumerate()
    {
        let inp = &case["inputs"];
        let exp = &case["outputs"];
        let r = tangent_flow_inversion_residual(
            f(&inp["candidate_chit"]),
            f(&inp["candidate_gamma"]),
            f(&inp["target_substrate_chit"]),
            f(&inp["target_substrate_gamma"]),
            f(&inp["delta_chit"]),
            f(&inp["delta_gamma"]),
            f(&inp["tau_obs"]),
            f(&inp["tau_obs_ref"]),
        );
        assert_close(
            r,
            f(&exp["residual"]),
            LIBM,
            &format!("tangent_flow_inversion_residual[{i}]"),
        );
    }
}

#[test]
fn jax_core_laplace_covariance_from_jacobian() {
    let fixture = load_fixture();
    for (i, case) in fixture["laplace_covariance_from_jacobian"]
        .as_array()
        .unwrap()
        .iter()
        .enumerate()
    {
        let inp = &case["inputs"];
        let exp = &case["outputs"];
        let j_rows = mat_f(&inp["jacobian"]);
        let j: Vec<[f64; 2]> = j_rows.iter().map(|row| [row[0], row[1]]).collect();
        let cov = laplace_covariance_from_jacobian(&j, f(&inp["noise_variance"]))
            .expect("non-singular");
        let expected = mat_f(&exp["covariance"]);
        for r in 0..2 {
            for c in 0..2 {
                assert_close(
                    cov[r][c],
                    expected[r][c],
                    LIBM,
                    &format!("laplace_covariance_from_jacobian[{i}][{r}][{c}]"),
                );
            }
        }
    }
}

#[test]
fn jax_core_laplace_covariance_from_hessian() {
    let fixture = load_fixture();
    for (i, case) in fixture["laplace_covariance_from_hessian"]
        .as_array()
        .unwrap()
        .iter()
        .enumerate()
    {
        let inp = &case["inputs"];
        let exp = &case["outputs"];
        let rows = mat_f(&inp["hessian"]);
        let h: [[f64; 2]; 2] = [[rows[0][0], rows[0][1]], [rows[1][0], rows[1][1]]];
        let cov = laplace_covariance_from_hessian(&h, f(&inp["noise_variance"]))
            .expect("non-singular");
        let expected = mat_f(&exp["covariance"]);
        for r in 0..2 {
            for c in 0..2 {
                assert_close(
                    cov[r][c],
                    expected[r][c],
                    LIBM,
                    &format!("laplace_covariance_from_hessian[{i}][{r}][{c}]"),
                );
            }
        }
    }
}

#[test]
fn jax_core_caputo_flow() {
    let fixture = load_fixture();
    for (i, case) in fixture["caputo_flow"].as_array().unwrap().iter().enumerate() {
        let inp = &case["inputs"];
        let exp = &case["outputs"];
        let amps = vec_f(&inp["prony_amplitudes"]);
        let decays = vec_f(&inp["prony_decays"]);
        let (chit, gamma) = caputo_flow(
            f(&inp["chit_0"]),
            f(&inp["gamma_ab_0"]),
            f(&inp["lambda_chit"]),
            f(&inp["lambda_gamma"]),
            f(&inp["nu"]),
            &amps,
            &decays,
        );
        assert_close(
            chit,
            f(&exp["chit"]),
            LIBM_WIDE,
            &format!("caputo_flow[{i}].chit"),
        );
        assert_close(
            gamma,
            f(&exp["gamma_ab"]),
            LIBM_WIDE,
            &format!("caputo_flow[{i}].gamma_ab"),
        );
    }
}

#[test]
fn jax_core_mlp_forward() {
    let fixture = load_fixture();
    for (i, case) in fixture["mlp_forward"].as_array().unwrap().iter().enumerate() {
        let inp = &case["inputs"];
        let exp = &case["outputs"];
        let x = vec_f(&inp["x"]);
        let layers = parse_layers(&inp["weights"]);
        let act = parse_activation(&inp["activation"]);
        let y = mlp_forward(&x, &layers, act);
        let expected = vec_f(&exp["y"]);
        assert_eq!(
            y.len(),
            expected.len(),
            "mlp_forward[{i}] length mismatch"
        );
        for (k, (got, want)) in y.iter().zip(expected.iter()).enumerate() {
            assert_close(*got, *want, LIBM_WIDE, &format!("mlp_forward[{i}][{k}]"));
        }
    }
}

#[test]
fn jax_core_learned_field_substrate() {
    let fixture = load_fixture();
    for (i, case) in fixture["learned_field_substrate"]
        .as_array()
        .unwrap()
        .iter()
        .enumerate()
    {
        let inp = &case["inputs"];
        let exp = &case["outputs"];
        let layers = parse_layers(&inp["weights"]);
        let act = parse_activation(&inp["activation"]);
        let (chit, gamma) = learned_field_substrate(
            f(&inp["chit"]),
            f(&inp["gamma_ab"]),
            f(&inp["tau_obs"]),
            f(&inp["tau_obs_ref"]),
            &layers,
            act,
        );
        assert_close(
            chit,
            f(&exp["chit"]),
            LIBM_WIDE,
            &format!("learned_field_substrate[{i}].chit"),
        );
        assert_close(
            gamma,
            f(&exp["gamma_ab"]),
            LIBM_WIDE,
            &format!("learned_field_substrate[{i}].gamma_ab"),
        );
    }
}

#[test]
fn jax_core_laplace_log_evidence() {
    let fixture = load_fixture();
    for (i, case) in fixture["laplace_log_evidence"]
        .as_array()
        .unwrap()
        .iter()
        .enumerate()
    {
        let inp = &case["inputs"];
        let exp = &case["outputs"];
        let rows = mat_f(&inp["hessian"]);
        let h: [[f64; 2]; 2] = [[rows[0][0], rows[0][1]], [rows[1][0], rows[1][1]]];
        let n_obs = inp["n_obs"].as_u64().expect("n_obs u64") as usize;
        let ev = laplace_log_evidence(
            f(&inp["residual_at_map"]),
            &h,
            f(&inp["noise_variance"]),
            n_obs,
        );
        assert_close(
            ev,
            f(&exp["log_evidence"]),
            LIBM_WIDE,
            &format!("laplace_log_evidence[{i}]"),
        );
    }
}

// ---------------------------------------------------------------------------
// Session 8 — tangent_flow_forward_jacobian (math.rs primitive)
// ---------------------------------------------------------------------------

/// Per-cell bit-identity for the 2x2 analytical Jacobian. Python emits
/// the matrix via `jax.jacfwd`; Rust encodes the diagonal form directly.
/// Single `pow` call per non-trivial entry → LIBM (4 ULP) tolerance.
#[test]
fn jax_core_tangent_flow_forward_jacobian() {
    let fixture = load_fixture();
    for case in fixture["tangent_flow_forward_jacobian"]
        .as_array()
        .expect("tangent_flow_forward_jacobian array")
    {
        let label = case["label"].as_str().unwrap_or("?");
        let inp = &case["inputs"];
        let jac = tangent_flow_forward_jacobian(
            f(&inp["delta_gamma"]),
            f(&inp["tau_obs"]),
            f(&inp["tau_obs_ref"]),
        );
        let exp = mat_f(&case["outputs"]["jacobian"]);
        assert_eq!(exp.len(), 2, "jacobian fixture row count");
        for i in 0..2 {
            assert_eq!(exp[i].len(), 2, "jacobian fixture col count [{i}]");
            for j in 0..2 {
                assert_close(
                    jac[i][j],
                    exp[i][j],
                    LIBM,
                    &format!("tangent_flow_forward_jacobian[{label}][{i}][{j}]"),
                );
            }
        }
    }
}

// ===========================================================================
// Session 4 — gfdr_model.rs primitives
// ===========================================================================

#[test]
fn gfdr_alpha_s_matches_python() {
    let fixture = load_fixture();
    for (i, case) in fixture["gfdr_alpha_s"].as_array().unwrap().iter().enumerate() {
        let chit = f(&case["inputs"]["chit"]);
        let expected = f(&case["outputs"]["alpha_s"]);
        assert_close(alpha_s(chit), expected, LIBM, &format!("alpha_s[{i}]"));
    }
}

#[test]
fn gfdr_plateau_height_matches_python() {
    let fixture = load_fixture();
    for (i, case) in fixture["gfdr_plateau_height"]
        .as_array()
        .unwrap()
        .iter()
        .enumerate()
    {
        let chit = f(&case["inputs"]["chit"]);
        let expected = f(&case["outputs"]["plateau_height"]);
        assert_close(
            plateau_height(chit),
            expected,
            LIBM,
            &format!("plateau_height[{i}]"),
        );
    }
}

#[test]
fn gfdr_vertex_regime_matches_python() {
    // String-equality test — no ULP budget needed.
    let fixture = load_fixture();
    for (i, case) in fixture["gfdr_vertex_regime"]
        .as_array()
        .unwrap()
        .iter()
        .enumerate()
    {
        let chit = f(&case["inputs"]["chit"]);
        // Python emits the regime as its `Literal` string; serde reads
        // it back into our enum via `rename_all = "snake_case"`.
        let want: RegimeLabel = serde_json::from_value(case["outputs"]["regime"].clone())
            .expect("regime string parses to enum");
        assert_eq!(
            vertex_regime(chit),
            want,
            "vertex_regime[{i}] chit={chit}"
        );
    }
}

#[test]
fn gfdr_generate_locus_matches_python() {
    let fixture = load_fixture();
    for (i, case) in fixture["gfdr_generate_locus"]
        .as_array()
        .unwrap()
        .iter()
        .enumerate()
    {
        let chit = f(&case["inputs"]["chit"]);
        let regime: RegimeLabel = serde_json::from_value(case["inputs"]["regime"].clone())
            .expect("regime parses");
        let locus = generate_locus(chit, regime);
        let want_tau = vec_f(&case["outputs"]["tau"]);
        let want_chi = vec_f(&case["outputs"]["chi"]);
        let want_c = vec_f(&case["outputs"]["C"]);
        assert_eq!(locus.len(), want_tau.len(), "generate_locus[{i}] length");
        for (k, p) in locus.iter().enumerate() {
            // `tau` is `tau_min * (tau_max/tau_min)^t` — same arithmetic
            // either side; LIBM budget covers libm-powf.
            assert_close(
                p.tau,
                want_tau[k],
                LIBM,
                &format!("generate_locus[{i}][{k}].tau"),
            );
            // `chi` and `C` compose exp / powf calls; the s-critical
            // branch sums two contributions → LIBM_WIDE.
            assert_close(
                p.chi,
                want_chi[k],
                LIBM_WIDE,
                &format!("generate_locus[{i}][{k}].chi"),
            );
            assert_close(
                p.c,
                want_c[k],
                LIBM_WIDE,
                &format!("generate_locus[{i}][{k}].C"),
            );
        }
    }
}

#[test]
fn gfdr_interp_locus_matches_python() {
    let fixture = load_fixture();
    for (i, case) in fixture["gfdr_interp_locus"]
        .as_array()
        .unwrap()
        .iter()
        .enumerate()
    {
        let chit = f(&case["inputs"]["chit"]);
        let tau = f(&case["inputs"]["tau"]);
        let regime = vertex_regime(chit);
        let locus = generate_locus(chit, regime);
        let (c, chi) = interp_locus(&locus, tau);
        assert_close(
            c,
            f(&case["outputs"]["C"]),
            LIBM,
            &format!("interp_locus[{i}].C"),
        );
        assert_close(
            chi,
            f(&case["outputs"]["chi"]),
            LIBM,
            &format!("interp_locus[{i}].chi"),
        );
    }
}

#[test]
fn gfdr_locus_residual_matches_python() {
    let fixture = load_fixture();
    for (i, case) in fixture["gfdr_locus_residual"]
        .as_array()
        .unwrap()
        .iter()
        .enumerate()
    {
        let candidate = f(&case["inputs"]["candidate_chit"]);
        let rows: Vec<EmpiricalRow> = case["inputs"]["empirical"]
            .as_array()
            .unwrap()
            .iter()
            .map(|row| EmpiricalRow {
                tau: f(&row["tau"]),
                chi: f(&row["chi"]),
                c: f(&row["C"]),
            })
            .collect();
        let r = locus_residual(&rows, candidate);
        // Five-term mean of squared diffs of `(C, chi)` against
        // interpolated locus values; cumulative reduction order matters.
        assert_close(
            r,
            f(&case["outputs"]["residual"]),
            LIBM_WIDE,
            &format!("locus_residual[{i}]"),
        );
    }
}

// ===========================================================================
// Session 4 — sidecar.rs cross-language rounding
// ===========================================================================

#[test]
fn sidecar_round_key_matches_python() {
    let fixture = load_fixture();
    for (i, case) in fixture["sidecar_round_key"]
        .as_array()
        .unwrap()
        .iter()
        .enumerate()
    {
        let chit = f(&case["inputs"]["chit"]);
        let gamma = f(&case["inputs"]["gamma_AB"]);
        let tau = f(&case["inputs"]["tau_obs"]);
        let decimals = case["inputs"]["decimals"].as_i64().unwrap() as i32;
        let (r_chit, r_gamma, r_tau) = round_key(chit, gamma, tau, decimals);
        // Python `round` and Rust `round_ties_even` can disagree by 1 ULP
        // at the rounded precision in pathological halfway cases; LIBM=4
        // covers everything the typical Banach-sidecar producer emits.
        assert_close(
            r_chit,
            f(&case["outputs"]["chit"]),
            LIBM,
            &format!("round_key[{i}].chit"),
        );
        assert_close(
            r_gamma,
            f(&case["outputs"]["gamma_AB"]),
            LIBM,
            &format!("round_key[{i}].gamma_AB"),
        );
        assert_close(
            r_tau,
            f(&case["outputs"]["tau_obs"]),
            LIBM,
            &format!("round_key[{i}].tau_obs"),
        );
    }
}

// ===========================================================================
// Session 4 — flow.rs dispatch (banach_exp / generic / Caputo)
// ===========================================================================

fn build_tangent_flow_field(inputs: &Value) -> TangentFlowField {
    let refinement: Option<BTreeMap<String, Value>> = match &inputs["refinement"] {
        Value::Null => None,
        Value::Object(map) => Some(map.iter().map(|(k, v)| (k.clone(), v.clone())).collect()),
        other => panic!("unexpected refinement shape: {other:?}"),
    };
    let origin = TranslationRule {
        operating_point: OperatingPoint {
            label: "origin".to_string(),
            gt: Gt::S,
            axes: BTreeMap::new(),
        },
        xdot_choice: "default".to_string(),
        canonical: CanonicalPoint {
            chit: 0.0,
            gamma_AB: 0.0,
            k_frust: false,
            method: "test".to_string(),
            extras: BTreeMap::new(),
        },
    };
    TangentFlowField {
        direction: Direction::Forward,
        rule_at_origin: origin,
        scaling: ScalingRule {
            tau_obs_ref: f(&inputs["tau_obs_ref"]),
            delta_chit: f(&inputs["delta_chit"]),
            delta_gamma: f(&inputs["delta_gamma"]),
            refinement,
        },
        description: None,
    }
}

#[test]
fn flow_matches_python_across_dispatch() {
    let fixture = load_fixture();
    for (i, case) in fixture["flow"].as_array().unwrap().iter().enumerate() {
        let inputs = &case["inputs"];
        let field = TranslationField::TangentFlow(build_tangent_flow_field(inputs));
        let initial = CanonicalState {
            chit: f(&inputs["chit_0"]),
            gamma_AB: f(&inputs["gamma_AB_0"]),
            k_frust: false,
        };
        let nu = f(&inputs["nu"]);
        let out = flow(&initial, nu, &field).expect("flow dispatch should succeed");
        // Branch budget: banach_exp / generic compose ≤ 2 libm calls per
        // axis (LIBM); Caputo sums prony_terms.len() exp() calls
        // sequentially (LIBM_WIDE for multi-term cases).
        let budget = if inputs["refinement"]["prony_terms"]
            .as_array()
            .map(|a| a.len() > 1)
            .unwrap_or(false)
        {
            LIBM_WIDE
        } else {
            LIBM
        };
        assert_close(
            out.chit,
            f(&case["outputs"]["chit"]),
            budget,
            &format!("flow[{i}].chit"),
        );
        assert_close(
            out.gamma_AB,
            f(&case["outputs"]["gamma_AB"]),
            budget,
            &format!("flow[{i}].gamma_AB"),
        );
    }
}

// ---------------------------------------------------------------------------
// Session 6 — intent algebra Python→Rust JSON parity
// ---------------------------------------------------------------------------
//
// Not bit-identity (intent_map is pure arithmetic dispatch, no libm) —
// this is a *schema parity* contract. Python is the sacrifice producer
// in the wrapped-variant path (session 7); the test asserts that
// Python-emitted sacrifice JSON deserializes cleanly into the Rust
// `SacrificeRecord` flat-dict shape and reproduces every field.
//
// Asymmetric parity by design: Python's sac dict contains a stored
// `preserved_invariant` STRING key. Rust's `SacrificeRecord` exposes
// the same string via a derived `.preserved_invariant()` method (no
// stored field) — the string is statically determined by the
// `IntentDiagnostics` variant per the BLOCK_IN-prep rationale. serde
// silently drops the unknown field on Python→Rust read. Rust→Python
// round-trip would lose the key; if a future consumer ever needs
// symmetric round-trip, add a custom Serialize on SacrificeRecord
// emitting `preserved_invariant` from the derived method (the BLOCK_IN
// note flags this option). The test asserts the asymmetric path
// works AND that the derived `.preserved_invariant()` matches Python's
// emitted string byte-for-byte, so symmetric parity is a one-line
// serializer away should it ever be needed.

fn parse_intent_id(s: &str) -> IntentId {
    match s {
        "I1" => IntentId::I1,
        "I2" => IntentId::I2,
        "I3" => IntentId::I3,
        "I4" => IntentId::I4,
        "I5" => IntentId::I5,
        other => panic!("unknown intent id in fixture: {other}"),
    }
}

#[test]
fn sacrifice_record_python_to_rust_json_parity() {
    let fixture = load_fixture();
    let cases = fixture["sacrifice_record"]
        .as_array()
        .expect("sacrifice_record array");
    assert!(!cases.is_empty(), "sacrifice_record fixture must be non-empty");
    let mut intents_seen = std::collections::HashSet::new();

    for (i, case) in cases.iter().enumerate() {
        let label = format!("sacrifice_record[{i}]");
        let inputs = &case["inputs"];
        let outputs = &case["outputs"];
        let sac_json = &outputs["sacrifice"];
        let mapped_json = &outputs["mapped"];

        // --- Deserialize: Python's sac dict → Rust SacrificeRecord.
        let rust_sac: SacrificeRecord = serde_json::from_value(sac_json.clone())
            .unwrap_or_else(|e| {
                panic!("{label}: SacrificeRecord deserialize failed: {e}\njson: {sac_json}")
            });

        // --- Deserialize: Python's mapped state → Rust CanonicalState
        // (smoke check that CanonicalState shape matches at the same
        // boundary; the mapped state rides alongside the sacrifice).
        let rust_mapped: CanonicalState = serde_json::from_value(mapped_json.clone())
            .unwrap_or_else(|e| {
                panic!("{label}: CanonicalState deserialize failed: {e}\njson: {mapped_json}")
            });
        let expected_chit = f(&mapped_json["chit"]);
        let expected_gamma = f(&mapped_json["gamma_AB"]);
        assert_eq!(rust_mapped.chit, expected_chit, "{label}: mapped.chit");
        assert_eq!(rust_mapped.gamma_AB, expected_gamma, "{label}: mapped.gamma_AB");
        assert_eq!(
            rust_mapped.k_frust,
            mapped_json["k_frust"].as_bool().expect("k_frust bool"),
            "{label}: mapped.k_frust",
        );

        // --- Common-field parity (outer SacrificeRecord struct).
        let expected_invariant = sac_json["invariant_preserved"]
            .as_bool()
            .expect("invariant_preserved bool");
        assert_eq!(
            rust_sac.invariant_preserved, expected_invariant,
            "{label}: invariant_preserved",
        );
        assert_eq!(
            rust_sac.delta_chit, f(&sac_json["delta_chit"]),
            "{label}: delta_chit",
        );
        assert_eq!(
            rust_sac.delta_gamma_AB, f(&sac_json["delta_gamma_AB"]),
            "{label}: delta_gamma_AB",
        );

        // --- Derived methods match Python's stored strings.
        let expected_intent = parse_intent_id(
            sac_json["intent"].as_str().expect("intent string"),
        );
        assert_eq!(rust_sac.intent(), expected_intent, "{label}: intent()");

        let expected_preserved = sac_json["preserved_invariant"]
            .as_str()
            .expect("preserved_invariant string");
        assert_eq!(
            rust_sac.preserved_invariant(), expected_preserved,
            "{label}: preserved_invariant() derived string",
        );

        // --- Cross-check with the original (state, gamut, intent) inputs.
        // The fixture inputs document the test case; the intent_id field
        // must agree with the sac's intent tag (sanity).
        let intent_input = parse_intent_id(
            inputs["intent_id"].as_str().expect("intent_id string"),
        );
        assert_eq!(
            rust_sac.intent(), intent_input,
            "{label}: sac.intent() must match inputs.intent_id",
        );
        intents_seen.insert(intent_input);

        // --- Per-intent diagnostic parity.
        match (&rust_sac.diagnostics, expected_intent) {
            (
                IntentDiagnostics::I1 {
                    regime_preserved,
                    gamma_AB_sign_preserved,
                    k_frust_preserved,
                    original_regime,
                    mapped_regime,
                    original_gamma_AB_sign,
                    mapped_gamma_AB_sign,
                },
                IntentId::I1,
            ) => {
                assert_eq!(
                    *regime_preserved,
                    sac_json["regime_preserved"].as_bool().expect("bool"),
                    "{label}: I1.regime_preserved",
                );
                assert_eq!(
                    *gamma_AB_sign_preserved,
                    sac_json["gamma_AB_sign_preserved"].as_bool().expect("bool"),
                    "{label}: I1.gamma_AB_sign_preserved",
                );
                assert_eq!(
                    *k_frust_preserved,
                    sac_json["k_frust_preserved"].as_bool().expect("bool"),
                    "{label}: I1.k_frust_preserved",
                );
                let py_orig = sac_json["original_regime"].as_str().expect("regime str");
                let py_mapped = sac_json["mapped_regime"].as_str().expect("regime str");
                assert_eq!(
                    serde_json::to_string(original_regime).unwrap(),
                    format!("\"{py_orig}\""),
                    "{label}: I1.original_regime",
                );
                assert_eq!(
                    serde_json::to_string(mapped_regime).unwrap(),
                    format!("\"{py_mapped}\""),
                    "{label}: I1.mapped_regime",
                );
                assert_eq!(
                    *original_gamma_AB_sign as i64,
                    sac_json["original_gamma_AB_sign"].as_i64().expect("i64"),
                    "{label}: I1.original_gamma_AB_sign",
                );
                assert_eq!(
                    *mapped_gamma_AB_sign as i64,
                    sac_json["mapped_gamma_AB_sign"].as_i64().expect("i64"),
                    "{label}: I1.mapped_gamma_AB_sign",
                );
            }
            (
                IntentDiagnostics::I2 {
                    out_of_gamut_rejected,
                    out_of_gamut_axes,
                },
                IntentId::I2,
            ) => {
                assert_eq!(
                    *out_of_gamut_rejected,
                    sac_json["out_of_gamut_rejected"].as_bool().expect("bool"),
                    "{label}: I2.out_of_gamut_rejected",
                );
                let py_axes: Vec<&str> = sac_json["out_of_gamut_axes"]
                    .as_array()
                    .expect("axes array")
                    .iter()
                    .map(|v| v.as_str().expect("axis str"))
                    .collect();
                assert_eq!(
                    out_of_gamut_axes.len(),
                    py_axes.len(),
                    "{label}: I2.out_of_gamut_axes length",
                );
                for (a, b) in out_of_gamut_axes.iter().zip(py_axes.iter()) {
                    assert_eq!(a, b, "{label}: I2.out_of_gamut_axes element");
                }
            }
            (
                IntentDiagnostics::I3 {
                    capacity_class,
                    mapped_capacity_class,
                    k_frust,
                    k_frust_preserved,
                },
                IntentId::I3,
            ) => {
                let py_cap = sac_json["capacity_class"].as_str().expect("cap str");
                let py_mcap = sac_json["mapped_capacity_class"].as_str().expect("cap str");
                let expected_cap = match py_cap {
                    "deep" => CapacityClass::Deep,
                    "shallow" => CapacityClass::Shallow,
                    other => panic!("{label}: unknown capacity_class: {other}"),
                };
                let expected_mcap = match py_mcap {
                    "deep" => CapacityClass::Deep,
                    "shallow" => CapacityClass::Shallow,
                    other => panic!("{label}: unknown mapped_capacity_class: {other}"),
                };
                assert_eq!(*capacity_class, expected_cap, "{label}: I3.capacity_class");
                assert_eq!(
                    *mapped_capacity_class, expected_mcap,
                    "{label}: I3.mapped_capacity_class",
                );
                assert_eq!(
                    *k_frust,
                    sac_json["k_frust"].as_bool().expect("bool"),
                    "{label}: I3.k_frust",
                );
                assert_eq!(
                    *k_frust_preserved,
                    sac_json["k_frust_preserved"].as_bool().expect("bool"),
                    "{label}: I3.k_frust_preserved",
                );
            }
            (
                IntentDiagnostics::I4 {
                    original_gamma_AB_sign,
                    mapped_gamma_AB_sign,
                },
                IntentId::I4,
            ) => {
                assert_eq!(
                    *original_gamma_AB_sign as i64,
                    sac_json["original_gamma_AB_sign"].as_i64().expect("i64"),
                    "{label}: I4.original_gamma_AB_sign",
                );
                assert_eq!(
                    *mapped_gamma_AB_sign as i64,
                    sac_json["mapped_gamma_AB_sign"].as_i64().expect("i64"),
                    "{label}: I4.mapped_gamma_AB_sign",
                );
            }
            (
                IntentDiagnostics::I5 {
                    regime_preserved,
                    original_regime,
                    mapped_regime,
                },
                IntentId::I5,
            ) => {
                assert_eq!(
                    *regime_preserved,
                    sac_json["regime_preserved"].as_bool().expect("bool"),
                    "{label}: I5.regime_preserved",
                );
                let py_orig = sac_json["original_regime"].as_str().expect("regime str");
                let py_mapped = sac_json["mapped_regime"].as_str().expect("regime str");
                assert_eq!(
                    serde_json::to_string(original_regime).unwrap(),
                    format!("\"{py_orig}\""),
                    "{label}: I5.original_regime",
                );
                assert_eq!(
                    serde_json::to_string(mapped_regime).unwrap(),
                    format!("\"{py_mapped}\""),
                    "{label}: I5.mapped_regime",
                );
            }
            (variant, expected) => panic!(
                "{label}: variant/intent mismatch — Rust variant {variant:?}, expected {expected:?}",
            ),
        }
    }

    // Coverage: every intent should be exercised at least once.
    for required in [IntentId::I1, IntentId::I2, IntentId::I3, IntentId::I4, IntentId::I5] {
        assert!(
            intents_seen.contains(&required),
            "sacrifice_record fixture missing case for {required:?}",
        );
    }
}

// ---------------------------------------------------------------------------
// Session 7 — provenance + wrapped-variant wire parity
// ---------------------------------------------------------------------------

fn parse_dispatch_path(s: &str) -> DispatchPath {
    match s {
        "direct_compute" => DispatchPath::DirectCompute,
        "table_hit" => DispatchPath::TableHit,
        "compute_fallback" => DispatchPath::ComputeFallback,
        other => panic!("unknown dispatch_path: {other}"),
    }
}

fn regime_label_str(label: RegimeLabel) -> &'static str {
    match label {
        RegimeLabel::DeepC => "deep_c",
        RegimeLabel::CNearS => "c_near_s",
        RegimeLabel::SCritical => "s_critical",
        RegimeLabel::RNearS => "r_near_s",
        RegimeLabel::DeepR => "deep_r",
    }
}

/// Cross-language bit-identity for `provenance_hash`.
///
/// The contract is on the **raw 4-byte blake2b digest**, not the
/// float view: the digest is bit-stable and serializes losslessly as
/// hex, while the `n / 2^32` float view cannot round-trip through
/// JSON's decimal-string representation under naive parsers (1-ULP
/// drift on some bit patterns; rational hash → no tolerance budget).
/// Comparing digests sidesteps the wire-format risk entirely.
///
/// Any drift in the
/// `(solver_version | operation | dispatch_path | table_version)`
/// payload encoding breaks the EXR-channel provenance fingerprint
/// contract.
#[test]
fn provenance_hash_python_to_rust_parity() {
    let fixture = load_fixture();
    let cases = fixture["provenance_hash"]
        .as_array()
        .expect("provenance_hash array");
    assert!(!cases.is_empty(), "provenance_hash fixture must be non-empty");

    for (i, case) in cases.iter().enumerate() {
        let inputs = &case["inputs"];
        let op = inputs["operation"].as_str().expect("operation str");
        let dp_str = inputs["dispatch_path"].as_str().expect("dispatch_path str");
        let dp = parse_dispatch_path(dp_str);
        let tv = inputs["table_version"].as_str().map(|s| s.to_string());
        let expected_hex = case["output_bits_hex"]
            .as_str()
            .expect("output_bits_hex str");

        let prov = make_provenance(op, dp, tv.clone(), Vec::new());
        let actual_bytes = provenance_digest_bytes(&prov);
        let actual_hex = actual_bytes
            .iter()
            .map(|b| format!("{b:02x}"))
            .collect::<String>();

        assert_eq!(
            actual_hex, expected_hex,
            "provenance_hash[{i}] ({op}, {dp_str}, {tv:?}): \
             digest hex mismatch",
        );
    }

    // Coverage: every dispatch path should appear at least once, and at
    // least one table_version=null + at least one table_version=string.
    let mut dps: BTreeMap<String, bool> = BTreeMap::new();
    let mut has_null_tv = false;
    let mut has_str_tv = false;
    for case in cases {
        let dp = case["inputs"]["dispatch_path"].as_str().unwrap();
        dps.insert(dp.to_string(), true);
        if case["inputs"]["table_version"].is_null() {
            has_null_tv = true;
        } else {
            has_str_tv = true;
        }
    }
    for required in ["direct_compute", "table_hit", "compute_fallback"] {
        assert!(
            dps.contains_key(required),
            "provenance_hash fixture missing dispatch_path={required}",
        );
    }
    assert!(has_null_tv, "fixture missing a null table_version case");
    assert!(has_str_tv, "fixture missing a non-null table_version case");
}

/// Cross-language wire parity for `OperationOutput<RegimeReading>`.
///
/// Structured-field equality only: timestamps are non-deterministic
/// (Python uses `time.monotonic_ns()`, Rust uses `Instant`-elapsed),
/// and the notes diagnostic strings have a float-formatting divergence
/// (`f"{0.0}"` is `"0.0"` in Python, `format!("{}", 0.0)` is `"0"` in
/// Rust — see CLAUDE.md asymmetry note). Both exclusions are by design;
/// the load-bearing contract is the structured flags and the provenance
/// hash inputs.
#[test]
fn operation_output_regime_at_python_to_rust_parity() {
    let fixture = load_fixture();
    let cases = fixture["operation_output_regime_at"]
        .as_array()
        .expect("operation_output_regime_at array");
    assert!(
        !cases.is_empty(),
        "operation_output_regime_at fixture must be non-empty",
    );

    for case in cases {
        let label = case["label"].as_str().unwrap_or("<unlabeled>");
        let inputs = &case["inputs"];
        let canonical = CanonicalState {
            chit: inputs["chit"].as_f64().expect("chit"),
            gamma_AB: inputs["gamma_AB"].as_f64().expect("gamma_AB"),
            k_frust: inputs["k_frust"].as_bool().expect("k_frust"),
        };
        let tau_obs = inputs["tau_obs"].as_f64().expect("tau_obs");

        let out = regime_at_wrapped(&canonical, tau_obs);
        let expected = &case["output"];

        // value: regime label string + k_frust bool
        let py_regime = expected["value"]["regime"].as_str().unwrap();
        assert_eq!(
            regime_label_str(out.value.regime),
            py_regime,
            "{label}: value.regime",
        );
        assert_eq!(
            out.value.k_frust,
            expected["value"]["k_frust"].as_bool().unwrap(),
            "{label}: value.k_frust",
        );

        // validation: three structured flags. Notes excluded per the
        // documented float-formatting asymmetry above.
        assert_eq!(
            out.validation.asymptotic_closure_compliant,
            expected["validation"]["asymptotic_closure_compliant"]
                .as_bool()
                .unwrap(),
            "{label}: asymptotic_closure_compliant",
        );
        assert_eq!(
            out.validation.k_frust_invariant,
            expected["validation"]["k_frust_invariant"].as_bool().unwrap(),
            "{label}: k_frust_invariant",
        );
        let py_rt = &expected["validation"]["round_trip_residual"];
        match (out.validation.round_trip_residual, py_rt) {
            (None, v) if v.is_null() => (),
            (Some(actual), v) if v.is_f64() => {
                // Tolerance, not bit-equality: `round_trip_residual` is
                // a computed L2 norm (forward-then-back via the
                // translation field), so the cross-language contract
                // is convergence to the same value, not bit-identity.
                // Going through JSON's decimal-string form drops up to
                // 1 ULP under naive parsers anyway. LIBM_WIDE absorbs
                // both the wire-format drift and the libm reduction-
                // order difference.
                assert_close(
                    actual,
                    v.as_f64().unwrap(),
                    LIBM_WIDE,
                    &format!("{label}: round_trip_residual"),
                );
            }
            other => panic!(
                "{label}: round_trip_residual mismatch — Rust {:?}, Python {py_rt}",
                other.0,
            ),
        }

        // provenance: solver_version + operation + dispatch_path + table_version.
        // timestamp_ns excluded (non-deterministic; both impls are monotonic
        // but the reference epoch is process-local on each side).
        assert_eq!(
            out.provenance.solver_version,
            expected["provenance"]["solver_version"].as_str().unwrap(),
            "{label}: solver_version",
        );
        assert_eq!(
            out.provenance.solver_version, SOLVER_VERSION,
            "{label}: Rust SOLVER_VERSION must equal Python __version__",
        );
        assert_eq!(
            out.provenance.operation,
            expected["provenance"]["operation"].as_str().unwrap(),
            "{label}: operation",
        );
        assert_eq!(
            out.provenance.dispatch_path,
            parse_dispatch_path(
                expected["provenance"]["dispatch_path"].as_str().unwrap()
            ),
            "{label}: dispatch_path",
        );
        let py_tv = expected["provenance"]["table_version"].as_str();
        assert_eq!(
            out.provenance.table_version.as_deref(),
            py_tv,
            "{label}: table_version",
        );
    }
}

// ---------------------------------------------------------------------------
// Session 8 — operation_output_posterior wrapped-variant wire parity
// ---------------------------------------------------------------------------

/// Cross-language schema parity for
/// `forward_sweep_invert_posterior_wrapped` — Session 8 extension of
/// session 7's `operation_output_regime_at` template.
///
/// Each fixture case reconstructs the field shape from the `label`
/// (four cases: tangent_flow_identity, tangent_flow_nonidentity,
/// lookup_table_top_k_5, lookup_table_k_eq_1), calls the Rust wrapped
/// op with the same inputs, and asserts:
///
///   * Posterior.mean.{chit, gamma_AB} via LIBM_WIDE ULP tolerance
///     (computed floats per fixture-discipline rule); k_frust bit-exact.
///   * Posterior.covariance via LIBM_WIDE on each of the 4 cells.
///   * Posterior.noise_variance bit-exact (input echo).
///   * Posterior.log_evidence: tolerated when Some, bit-exact null vs
///     bit-exact null otherwise.
///   * Posterior.modes count + per-element fields (LIBM_WIDE on floats).
///   * Posterior.notes bit-exact (the only float-formatted token would
///     be top_k, an integer — no Python/Rust `f"{0.0}"` vs `format!`
///     divergence).
///   * ValidationReport flags + round_trip_residual.
///   * Provenance solver_version, operation, dispatch_path,
///     table_version. timestamps + notes excluded (same documented
///     asymmetry as the regime_at parity test).
#[test]
fn operation_output_posterior_python_to_rust_parity() {
    let fixture = load_fixture();
    let cases = fixture["operation_output_posterior"]
        .as_array()
        .expect("operation_output_posterior array");
    assert!(
        !cases.is_empty(),
        "operation_output_posterior fixture must be non-empty",
    );

    for case in cases {
        let label = case["label"].as_str().unwrap_or("<unlabeled>");
        let inputs = &case["inputs"];
        let tau_obs = inputs["tau_obs"].as_f64().expect("tau_obs");
        let noise_variance = inputs["noise_variance"].as_f64().expect("noise_variance");
        let top_k = inputs["top_k"].as_u64().expect("top_k") as usize;
        let s_chit = inputs["s_chit"].as_f64().expect("s_chit");
        let s_gamma_AB = inputs["s_gamma_AB"].as_f64().expect("s_gamma_AB");

        let target = posterior_substrate(s_chit, s_gamma_AB, tau_obs);
        let (field, grid_opt) = build_posterior_field(label);
        let out = forward_sweep_invert_posterior_wrapped(
            &target,
            &field,
            tau_obs,
            grid_opt.as_deref(),
            noise_variance,
            false,
            None,
            top_k,
        )
        .unwrap_or_else(|e| panic!("{label}: wrapped posterior errored: {e:?}"));

        let expected = &case["output"];
        let py_value = &expected["value"];

        // value.mean
        let py_mean = &py_value["mean"];
        assert_close(
            out.value.mean.chit,
            py_mean["chit"].as_f64().unwrap(),
            LIBM_WIDE,
            &format!("{label}: mean.chit"),
        );
        assert_close(
            out.value.mean.gamma_AB,
            py_mean["gamma_AB"].as_f64().unwrap(),
            LIBM_WIDE,
            &format!("{label}: mean.gamma_AB"),
        );
        assert_eq!(
            out.value.mean.k_frust,
            py_mean["k_frust"].as_bool().unwrap(),
            "{label}: mean.k_frust",
        );

        // value.covariance — LIBM_WIDE per cell.
        let py_cov = mat_f(&py_value["covariance"]);
        for i in 0..2 {
            for j in 0..2 {
                assert_close(
                    out.value.covariance[i][j],
                    py_cov[i][j],
                    LIBM_WIDE,
                    &format!("{label}: covariance[{i}][{j}]"),
                );
            }
        }

        // value.noise_variance — input echo, bit-exact.
        assert_eq!(
            out.value.noise_variance.to_bits(),
            py_value["noise_variance"].as_f64().unwrap().to_bits(),
            "{label}: noise_variance",
        );

        // value.log_evidence — Option<f64>; tolerated when Some.
        let py_le = &py_value["log_evidence"];
        match (out.value.log_evidence, py_le) {
            (None, v) if v.is_null() => (),
            (Some(actual), v) if v.is_f64() => {
                assert_close(
                    actual,
                    v.as_f64().unwrap(),
                    LIBM_WIDE,
                    &format!("{label}: log_evidence"),
                );
            }
            other => panic!(
                "{label}: log_evidence mismatch — Rust {:?}, Python {py_le}",
                other.0,
            ),
        }

        // value.modes — count + element fields. Python's emit-condition is
        // tuple-equality on f64 (bit-exact); Rust mirrors via to_bits()
        // comparison. Both impls evaluate the same numerical inputs, so
        // the emit decision agrees.
        let py_modes = py_value["modes"].as_array().expect("modes array");
        assert_eq!(
            out.value.modes.len(),
            py_modes.len(),
            "{label}: modes.len",
        );
        for (i, (rust_mode, py_mode)) in out.value.modes.iter().zip(py_modes).enumerate() {
            assert_close(
                rust_mode.chit,
                py_mode["chit"].as_f64().unwrap(),
                LIBM_WIDE,
                &format!("{label}: modes[{i}].chit"),
            );
            assert_close(
                rust_mode.gamma_AB,
                py_mode["gamma_AB"].as_f64().unwrap(),
                LIBM_WIDE,
                &format!("{label}: modes[{i}].gamma_AB"),
            );
            assert_eq!(
                rust_mode.k_frust,
                py_mode["k_frust"].as_bool().unwrap(),
                "{label}: modes[{i}].k_frust",
            );
        }

        // value.notes — bit-exact (no float-format divergence in these strings).
        let py_notes = py_value["notes"]
            .as_array()
            .expect("notes array")
            .iter()
            .map(|v| v.as_str().unwrap().to_string())
            .collect::<Vec<_>>();
        assert_eq!(out.value.notes, py_notes, "{label}: notes");

        // validation flags + round_trip_residual (matches regime_at parity).
        assert_eq!(
            out.validation.asymptotic_closure_compliant,
            expected["validation"]["asymptotic_closure_compliant"]
                .as_bool()
                .unwrap(),
            "{label}: asymptotic_closure_compliant",
        );
        assert_eq!(
            out.validation.k_frust_invariant,
            expected["validation"]["k_frust_invariant"].as_bool().unwrap(),
            "{label}: k_frust_invariant",
        );
        let py_rt = &expected["validation"]["round_trip_residual"];
        assert!(
            py_rt.is_null() && out.validation.round_trip_residual.is_none(),
            "{label}: posterior wrapped variant always emits None round_trip_residual",
        );

        // provenance fields (timestamps + notes excluded).
        assert_eq!(
            out.provenance.solver_version,
            expected["provenance"]["solver_version"].as_str().unwrap(),
            "{label}: solver_version",
        );
        assert_eq!(
            out.provenance.solver_version, SOLVER_VERSION,
            "{label}: Rust SOLVER_VERSION must equal Python __version__",
        );
        assert_eq!(
            out.provenance.operation,
            expected["provenance"]["operation"].as_str().unwrap(),
            "{label}: operation",
        );
        assert_eq!(
            out.provenance.dispatch_path,
            parse_dispatch_path(
                expected["provenance"]["dispatch_path"].as_str().unwrap()
            ),
            "{label}: dispatch_path",
        );
        let py_tv = expected["provenance"]["table_version"].as_str();
        assert_eq!(
            out.provenance.table_version.as_deref(),
            py_tv,
            "{label}: table_version",
        );
    }
}

fn posterior_substrate(s_chit: f64, s_gamma_AB: f64, tau_obs: f64) -> SubstrateState {
    let mut observables: BTreeMap<String, f64> = BTreeMap::new();
    observables.insert("substrate_chit".to_string(), s_chit);
    observables.insert("substrate_gamma_AB".to_string(), s_gamma_AB);
    SubstrateState {
        tau_obs,
        label: None,
        axes: BTreeMap::new(),
        observables,
    }
}

fn build_posterior_field(label: &str) -> (TranslationField, Option<Vec<[f64; 2]>>) {
    let origin = TranslationRule {
        operating_point: OperatingPoint {
            label: "origin".to_string(),
            gt: Gt::S,
            axes: BTreeMap::new(),
        },
        xdot_choice: "default".to_string(),
        canonical: CanonicalPoint {
            chit: 0.0,
            gamma_AB: 0.0,
            k_frust: false,
            method: "test".to_string(),
            extras: BTreeMap::new(),
        },
    };
    let lookup_rule = |label: &str, chit: f64, gamma_AB: f64| TranslationRule {
        operating_point: OperatingPoint {
            label: label.to_string(),
            gt: Gt::S,
            axes: {
                let mut m: BTreeMap<String, Value> = BTreeMap::new();
                m.insert("tau_obs".to_string(), Value::from(1.0));
                m
            },
        },
        xdot_choice: "default".to_string(),
        canonical: CanonicalPoint {
            chit,
            gamma_AB,
            k_frust: false,
            method: "test".to_string(),
            extras: BTreeMap::new(),
        },
    };
    match label {
        "tangent_flow_identity" => (
            TranslationField::TangentFlow(TangentFlowField {
                direction: Direction::Forward,
                rule_at_origin: origin,
                scaling: ScalingRule {
                    tau_obs_ref: 1.0,
                    delta_gamma: 0.0,
                    delta_chit: 0.0,
                    refinement: None,
                },
                description: None,
            }),
            None,
        ),
        "tangent_flow_nonidentity" => (
            TranslationField::TangentFlow(TangentFlowField {
                direction: Direction::Forward,
                rule_at_origin: origin,
                scaling: ScalingRule {
                    tau_obs_ref: 1.0,
                    delta_gamma: 0.5,
                    delta_chit: 0.3,
                    refinement: None,
                },
                description: None,
            }),
            None,
        ),
        "lookup_table_top_k_5" | "lookup_table_k_eq_1" => (
            TranslationField::LookupTable(LookupTableField {
                direction: Direction::Forward,
                rule: vec![
                    lookup_rule("a", 0.5, -0.3),
                    lookup_rule("b", 0.8, 0.2),
                    lookup_rule("c", -0.4, 0.4),
                ],
                description: None,
            }),
            Some(vec![[0.5, -0.3], [0.8, 0.2], [-0.4, 0.4]]),
        ),
        other => panic!("unknown posterior parity label: {other}"),
    }
}

// ---------------------------------------------------------------------------
// Session 7 followup — sidecar JSON wire-format parity (SIDECAR_FORMAT.md v1.0)
// ---------------------------------------------------------------------------

/// End-to-end cross-language parity for `InverseLookupSidecar`.
///
/// Python builds a small Banach sidecar via the v1 reference producer
/// (`BanachSubstrate.build_sidecar`), encodes it to JSON via
/// `encode_sidecar_to_json` (the spec-conformant serializer), and emits
/// the result as the `sidecar_wire_format` fixture entry. This test
/// deserializes the same JSON via serde and asserts:
///
/// 1. Structural metadata round-trips (wire_version, version,
///    driver_profile_id, rounding_decimals, grid lengths).
/// 2. Every `(canonical, tau)` from the canonical_grid hits via
///    `lookup_forward` and returns the recorded substrate (bit-identical
///    chit / gamma_AB observables).
/// 3. Every `(substrate, tau)` from the substrate_grid hits via
///    `lookup_inverse` and returns the recorded canonical (bit-identical
///    chit / gamma_AB / k_frust).
///
/// A successful run closes the BLOCK_IN §v6 session-9-open
/// "InverseLookupSidecar wire format" question: mpa-conform's curator
/// path is now writing to a frozen spec.
#[test]
fn sidecar_python_to_rust_parity() {
    let fixture = load_fixture();
    let cases = fixture["sidecar_wire_format"]
        .as_array()
        .expect("sidecar_wire_format array");
    assert!(
        !cases.is_empty(),
        "sidecar_wire_format fixture must be non-empty",
    );

    for case in cases {
        let label = case["label"].as_str().unwrap_or("<unlabeled>");

        // Deserialize the encoded sidecar via serde — the consumer
        // surface mpa-conform's curator path will write to.
        let sidecar: InverseLookupSidecar = serde_json::from_value(case["sidecar"].clone())
            .unwrap_or_else(|e| panic!("{label}: sidecar deserialize failed: {e}"));

        // ---- (1) structural metadata -----------------------------------
        assert_eq!(
            sidecar.wire_version, "1.0",
            "{label}: wire_version must be 1.0 per current spec",
        );
        assert_eq!(
            sidecar.rounding_decimals, DEFAULT_ROUNDING_DECIMALS,
            "{label}: rounding_decimals default mismatch",
        );
        assert!(
            !sidecar.driver_profile_id.is_empty(),
            "{label}: driver_profile_id must be non-empty",
        );
        assert_eq!(
            sidecar.tau_obs_grid.len(),
            sidecar.canonical_grid.len(),
            "{label}: tau_obs_grid and canonical_grid lengths must match",
        );
        assert_eq!(
            sidecar.tau_obs_grid.len(),
            sidecar.substrate_grid.len(),
            "{label}: tau_obs_grid and substrate_grid lengths must match",
        );
        assert_eq!(
            sidecar.forward_lookup.len(),
            sidecar.tau_obs_grid.len(),
            "{label}: forward_lookup must have one entry per grid frame",
        );
        assert_eq!(
            sidecar.inverse_lookup.len(),
            sidecar.tau_obs_grid.len(),
            "{label}: inverse_lookup must have one entry per grid frame",
        );

        // ---- (2) forward lookup hits ----------------------------------
        for (i, tau) in sidecar.tau_obs_grid.iter().enumerate() {
            let canonical = sidecar.canonical_grid[i].clone();
            let expected_substrate = &sidecar.substrate_grid[i];
            let hit = lookup_forward(&sidecar, &canonical, *tau, sidecar.rounding_decimals)
                .unwrap_or_else(|| {
                    panic!(
                        "{label}: lookup_forward miss at frame {i} \
                         (canonical={canonical:?}, tau={tau})",
                    )
                });
            // Substrate observables must include the canonical pair
            // names; their values must agree bit-for-bit with what the
            // producer recorded (`BanachSubstrate.substrate_at` emits
            // identity-translated substrates: substrate_chit == chit,
            // substrate_gamma_AB == gamma_AB).
            let got_chit = hit
                .observables
                .get("substrate_chit")
                .copied()
                .expect("substrate_chit on hit");
            let got_gamma = hit
                .observables
                .get("substrate_gamma_AB")
                .copied()
                .expect("substrate_gamma_AB on hit");
            let want_chit = expected_substrate
                .observables
                .get("substrate_chit")
                .copied()
                .expect("substrate_chit on expected");
            let want_gamma = expected_substrate
                .observables
                .get("substrate_gamma_AB")
                .copied()
                .expect("substrate_gamma_AB on expected");
            assert_eq!(
                got_chit.to_bits(),
                want_chit.to_bits(),
                "{label}: forward lookup substrate_chit at frame {i}",
            );
            assert_eq!(
                got_gamma.to_bits(),
                want_gamma.to_bits(),
                "{label}: forward lookup substrate_gamma_AB at frame {i}",
            );
        }

        // ---- (3) inverse lookup hits ----------------------------------
        for (i, tau) in sidecar.tau_obs_grid.iter().enumerate() {
            let substrate = &sidecar.substrate_grid[i];
            let expected_canonical = &sidecar.canonical_grid[i];
            let hit = lookup_inverse(&sidecar, substrate, *tau, sidecar.rounding_decimals)
                .unwrap_or_else(|| {
                    panic!(
                        "{label}: lookup_inverse miss at frame {i} \
                         (substrate observables={:?}, tau={tau})",
                        substrate.observables,
                    )
                });
            assert_eq!(
                hit.chit.to_bits(),
                expected_canonical.chit.to_bits(),
                "{label}: inverse lookup chit at frame {i}",
            );
            assert_eq!(
                hit.gamma_AB.to_bits(),
                expected_canonical.gamma_AB.to_bits(),
                "{label}: inverse lookup gamma_AB at frame {i}",
            );
            assert_eq!(
                hit.k_frust, expected_canonical.k_frust,
                "{label}: inverse lookup k_frust at frame {i}",
            );
        }

        // ---- bonus: round_key bit-identity --------------------------
        // The producer rounded with Python `float(np.rint(x*10**n))/10**n`;
        // Rust here rounds with `(x*10^n).round_ties_even()/10^n`. Both
        // produce identical f64 bits for every finite input. Spot-check
        // by re-rounding the first canonical and confirming it matches
        // what's stored in the lookup map's keys.
        let c0 = sidecar.canonical_grid[0].clone();
        let tau0 = sidecar.tau_obs_grid[0];
        let (rc, rg, rt) = round_key(c0.chit, c0.gamma_AB, tau0, sidecar.rounding_decimals);
        // The hit we obtained from lookup_forward used the exact same
        // rounding — if Python and Rust disagreed on rounding for this
        // input, the lookup_forward call above would have missed.
        // Verify the round_key output is at least finite + matches the
        // unrounded values to within the rounding precision.
        assert!(rc.is_finite() && rg.is_finite() && rt.is_finite());
    }
}
