//! Bit-identity tests vs the Python `jax_core` reference.
//!
//! `tests/fixtures/jax_core_reference.json` is generated by the
//! co-located `emit_jax_core_reference.py` script (running the v5 Python
//! `mpa_scale_solver.jax_core` primitives over a small input sweep).
//! Python is the canonical reference (per BLOCK_IN §v6 "Python is the
//! pseudo-code spec for v6"); these tests assert each Rust primitive in
//! `src/math.rs` reproduces the Python output within a per-primitive ULP
//! budget — the v6 acceptance "byte-identical for deterministic ops"
//! check, scoped to math.rs.
//!
//! Tolerance discipline (tiered per primitive per the user direction at
//! session start):
//!   - LIBM (4 ULPs): primitives composing a small number of libm calls
//!     (tangent_flow_*, banach_state, lookup_squared_distance,
//!     tangent_flow_canonical_inverse, laplace_covariance_*).
//!   - LIBM_WIDE (16 ULPs): primitives composing many libm calls and / or
//!     sums whose reduction order differs between JAX (pairwise) and Rust
//!     (sequential): caputo_flow, mlp_forward, learned_field_substrate,
//!     laplace_log_evidence.
//! No primitive currently qualifies as "pure arithmetic on every path"
//! (the v0 identity branches do, but they share a budget with their
//! libm-routing siblings).
//!
//! Regenerating the fixture: rerun `emit_jax_core_reference.py` and
//! commit the JSON diff. The test will catch unintended divergence on
//! the next `cargo test --release`.

use std::fs;
use std::path::PathBuf;

use mpa_scale_solver::math::{
    Activation, MlpLayer, banach_state, caputo_flow, laplace_covariance_from_hessian,
    laplace_covariance_from_jacobian, laplace_log_evidence, learned_field_substrate,
    lookup_squared_distance, mlp_forward, tangent_flow_canonical,
    tangent_flow_canonical_inverse, tangent_flow_inversion_residual, tangent_flow_substrate,
};
use serde_json::Value;

const LIBM: u64 = 4;
const LIBM_WIDE: u64 = 16;

// ---------------------------------------------------------------------------
// Fixture loading + JSON helpers
// ---------------------------------------------------------------------------

fn load_fixture() -> Value {
    let path =
        PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("tests/fixtures/jax_core_reference.json");
    let text = fs::read_to_string(&path)
        .unwrap_or_else(|e| panic!("could not read {}: {}", path.display(), e));
    serde_json::from_str(&text).expect("fixture JSON parse")
}

fn f(v: &Value) -> f64 {
    v.as_f64().expect("expected f64")
}
fn vec_f(v: &Value) -> Vec<f64> {
    v.as_array().expect("array").iter().map(f).collect()
}
fn vec_b(v: &Value) -> Vec<bool> {
    v.as_array()
        .expect("array")
        .iter()
        .map(|e| e.as_bool().expect("expected bool"))
        .collect()
}
fn mat_f(v: &Value) -> Vec<Vec<f64>> {
    v.as_array().expect("array").iter().map(vec_f).collect()
}

fn parse_layers(v: &Value) -> Vec<MlpLayer> {
    v.as_array()
        .expect("layers array")
        .iter()
        .map(|layer| MlpLayer {
            w: mat_f(&layer["w"]),
            b: vec_f(&layer["b"]),
        })
        .collect()
}

fn parse_activation(v: &Value) -> Activation {
    match v.as_str().expect("activation string") {
        "tanh" => Activation::Tanh,
        "relu" => Activation::Relu,
        other => panic!("unsupported activation: {other}"),
    }
}

// ---------------------------------------------------------------------------
// ULP comparison
// ---------------------------------------------------------------------------

/// Count ULPs between two f64 values. Returns `u64::MAX` for non-finite
/// or different-sign values (which always fail any finite tolerance).
fn ulps_between(a: f64, b: f64) -> u64 {
    if a == b {
        return 0;
    }
    if !a.is_finite() || !b.is_finite() {
        return u64::MAX;
    }
    if a.is_sign_negative() != b.is_sign_negative() {
        return u64::MAX;
    }
    a.to_bits().abs_diff(b.to_bits())
}

#[track_caller]
fn assert_close(actual: f64, expected: f64, tol_ulps: u64, label: &str) {
    if actual == expected {
        return;
    }
    let ulps = ulps_between(actual, expected);
    assert!(
        ulps <= tol_ulps,
        "{label}: actual={actual} expected={expected} differs by {ulps} ULPs (budget {tol_ulps})",
    );
}

// ---------------------------------------------------------------------------
// Fixture coverage guard — fails loudly if the emitter drops a primitive.
// ---------------------------------------------------------------------------

#[test]
fn fixture_covers_all_12_primitives() {
    let fixture = load_fixture();
    let obj = fixture.as_object().expect("top-level object");
    let expected = [
        "tangent_flow_substrate",
        "banach_state",
        "tangent_flow_canonical",
        "lookup_squared_distance",
        "tangent_flow_canonical_inverse",
        "tangent_flow_inversion_residual",
        "laplace_covariance_from_jacobian",
        "laplace_covariance_from_hessian",
        "caputo_flow",
        "mlp_forward",
        "learned_field_substrate",
        "laplace_log_evidence",
    ];
    assert_eq!(
        obj.len(),
        expected.len(),
        "fixture has {} primitives, expected {}",
        obj.len(),
        expected.len()
    );
    for name in expected {
        assert!(obj.contains_key(name), "fixture missing primitive: {name}");
    }
}

// ---------------------------------------------------------------------------
// Per-primitive bit-identity tests
// ---------------------------------------------------------------------------

#[test]
fn jax_core_tangent_flow_substrate() {
    let fixture = load_fixture();
    for (i, case) in fixture["tangent_flow_substrate"]
        .as_array()
        .unwrap()
        .iter()
        .enumerate()
    {
        let inp = &case["inputs"];
        let exp = &case["outputs"];
        let (chit, gamma) = tangent_flow_substrate(
            f(&inp["chit"]),
            f(&inp["gamma_ab"]),
            f(&inp["delta_chit"]),
            f(&inp["delta_gamma"]),
            f(&inp["tau_obs"]),
            f(&inp["tau_obs_ref"]),
        );
        assert_close(
            chit,
            f(&exp["chit"]),
            LIBM,
            &format!("tangent_flow_substrate[{i}].chit"),
        );
        assert_close(
            gamma,
            f(&exp["gamma_ab"]),
            LIBM,
            &format!("tangent_flow_substrate[{i}].gamma_ab"),
        );
    }
}

#[test]
fn jax_core_banach_state() {
    let fixture = load_fixture();
    for (i, case) in fixture["banach_state"].as_array().unwrap().iter().enumerate() {
        let inp = &case["inputs"];
        let exp = &case["outputs"];
        let (chit, gamma) = banach_state(
            f(&inp["chit_0"]),
            f(&inp["gamma_ab_0"]),
            f(&inp["lambda_chit"]),
            f(&inp["lambda_gamma"]),
            f(&inp["nu"]),
        );
        assert_close(
            chit,
            f(&exp["chit"]),
            LIBM,
            &format!("banach_state[{i}].chit"),
        );
        assert_close(
            gamma,
            f(&exp["gamma_ab"]),
            LIBM,
            &format!("banach_state[{i}].gamma_ab"),
        );
    }
}

#[test]
fn jax_core_tangent_flow_canonical() {
    let fixture = load_fixture();
    for (i, case) in fixture["tangent_flow_canonical"]
        .as_array()
        .unwrap()
        .iter()
        .enumerate()
    {
        let inp = &case["inputs"];
        let exp = &case["outputs"];
        let (chit, gamma) = tangent_flow_canonical(
            f(&inp["chit_0"]),
            f(&inp["gamma_ab_0"]),
            f(&inp["delta_chit"]),
            f(&inp["delta_gamma"]),
            f(&inp["nu"]),
            f(&inp["tau_obs_ref"]),
        );
        assert_close(
            chit,
            f(&exp["chit"]),
            LIBM,
            &format!("tangent_flow_canonical[{i}].chit"),
        );
        assert_close(
            gamma,
            f(&exp["gamma_ab"]),
            LIBM,
            &format!("tangent_flow_canonical[{i}].gamma_ab"),
        );
    }
}

#[test]
fn jax_core_lookup_squared_distance() {
    let fixture = load_fixture();
    for (i, case) in fixture["lookup_squared_distance"]
        .as_array()
        .unwrap()
        .iter()
        .enumerate()
    {
        let inp = &case["inputs"];
        let exp = &case["outputs"];
        let chits = vec_f(&inp["field_chits"]);
        let gammas = vec_f(&inp["field_gammas"]);
        let taus = vec_f(&inp["field_taus"]);
        let has_tau = vec_b(&inp["has_tau"]);
        let d = lookup_squared_distance(
            f(&inp["query_chit"]),
            f(&inp["query_gamma"]),
            &chits,
            &gammas,
            &taus,
            &has_tau,
            f(&inp["tau_obs"]),
            f(&inp["tau_obs_weight"]),
        );
        let expected = vec_f(&exp["d2"]);
        assert_eq!(
            d.len(),
            expected.len(),
            "lookup_squared_distance[{i}] length mismatch"
        );
        for (k, (got, want)) in d.iter().zip(expected.iter()).enumerate() {
            assert_close(
                *got,
                *want,
                LIBM,
                &format!("lookup_squared_distance[{i}][{k}]"),
            );
        }
    }
}

#[test]
fn jax_core_tangent_flow_canonical_inverse() {
    let fixture = load_fixture();
    for (i, case) in fixture["tangent_flow_canonical_inverse"]
        .as_array()
        .unwrap()
        .iter()
        .enumerate()
    {
        let inp = &case["inputs"];
        let exp = &case["outputs"];
        let (chit, gamma) = tangent_flow_canonical_inverse(
            f(&inp["substrate_chit"]),
            f(&inp["substrate_gamma_ab"]),
            f(&inp["delta_chit"]),
            f(&inp["delta_gamma"]),
            f(&inp["tau_obs"]),
            f(&inp["tau_obs_ref"]),
        );
        assert_close(
            chit,
            f(&exp["chit"]),
            LIBM,
            &format!("tangent_flow_canonical_inverse[{i}].chit"),
        );
        assert_close(
            gamma,
            f(&exp["gamma_ab"]),
            LIBM,
            &format!("tangent_flow_canonical_inverse[{i}].gamma_ab"),
        );
    }
}

#[test]
fn jax_core_tangent_flow_inversion_residual() {
    let fixture = load_fixture();
    for (i, case) in fixture["tangent_flow_inversion_residual"]
        .as_array()
        .unwrap()
        .iter()
        .enumerate()
    {
        let inp = &case["inputs"];
        let exp = &case["outputs"];
        let r = tangent_flow_inversion_residual(
            f(&inp["candidate_chit"]),
            f(&inp["candidate_gamma"]),
            f(&inp["target_substrate_chit"]),
            f(&inp["target_substrate_gamma"]),
            f(&inp["delta_chit"]),
            f(&inp["delta_gamma"]),
            f(&inp["tau_obs"]),
            f(&inp["tau_obs_ref"]),
        );
        assert_close(
            r,
            f(&exp["residual"]),
            LIBM,
            &format!("tangent_flow_inversion_residual[{i}]"),
        );
    }
}

#[test]
fn jax_core_laplace_covariance_from_jacobian() {
    let fixture = load_fixture();
    for (i, case) in fixture["laplace_covariance_from_jacobian"]
        .as_array()
        .unwrap()
        .iter()
        .enumerate()
    {
        let inp = &case["inputs"];
        let exp = &case["outputs"];
        let j_rows = mat_f(&inp["jacobian"]);
        let j: Vec<[f64; 2]> = j_rows.iter().map(|row| [row[0], row[1]]).collect();
        let cov = laplace_covariance_from_jacobian(&j, f(&inp["noise_variance"]))
            .expect("non-singular");
        let expected = mat_f(&exp["covariance"]);
        for r in 0..2 {
            for c in 0..2 {
                assert_close(
                    cov[r][c],
                    expected[r][c],
                    LIBM,
                    &format!("laplace_covariance_from_jacobian[{i}][{r}][{c}]"),
                );
            }
        }
    }
}

#[test]
fn jax_core_laplace_covariance_from_hessian() {
    let fixture = load_fixture();
    for (i, case) in fixture["laplace_covariance_from_hessian"]
        .as_array()
        .unwrap()
        .iter()
        .enumerate()
    {
        let inp = &case["inputs"];
        let exp = &case["outputs"];
        let rows = mat_f(&inp["hessian"]);
        let h: [[f64; 2]; 2] = [[rows[0][0], rows[0][1]], [rows[1][0], rows[1][1]]];
        let cov = laplace_covariance_from_hessian(&h, f(&inp["noise_variance"]))
            .expect("non-singular");
        let expected = mat_f(&exp["covariance"]);
        for r in 0..2 {
            for c in 0..2 {
                assert_close(
                    cov[r][c],
                    expected[r][c],
                    LIBM,
                    &format!("laplace_covariance_from_hessian[{i}][{r}][{c}]"),
                );
            }
        }
    }
}

#[test]
fn jax_core_caputo_flow() {
    let fixture = load_fixture();
    for (i, case) in fixture["caputo_flow"].as_array().unwrap().iter().enumerate() {
        let inp = &case["inputs"];
        let exp = &case["outputs"];
        let amps = vec_f(&inp["prony_amplitudes"]);
        let decays = vec_f(&inp["prony_decays"]);
        let (chit, gamma) = caputo_flow(
            f(&inp["chit_0"]),
            f(&inp["gamma_ab_0"]),
            f(&inp["lambda_chit"]),
            f(&inp["lambda_gamma"]),
            f(&inp["nu"]),
            &amps,
            &decays,
        );
        assert_close(
            chit,
            f(&exp["chit"]),
            LIBM_WIDE,
            &format!("caputo_flow[{i}].chit"),
        );
        assert_close(
            gamma,
            f(&exp["gamma_ab"]),
            LIBM_WIDE,
            &format!("caputo_flow[{i}].gamma_ab"),
        );
    }
}

#[test]
fn jax_core_mlp_forward() {
    let fixture = load_fixture();
    for (i, case) in fixture["mlp_forward"].as_array().unwrap().iter().enumerate() {
        let inp = &case["inputs"];
        let exp = &case["outputs"];
        let x = vec_f(&inp["x"]);
        let layers = parse_layers(&inp["weights"]);
        let act = parse_activation(&inp["activation"]);
        let y = mlp_forward(&x, &layers, act);
        let expected = vec_f(&exp["y"]);
        assert_eq!(
            y.len(),
            expected.len(),
            "mlp_forward[{i}] length mismatch"
        );
        for (k, (got, want)) in y.iter().zip(expected.iter()).enumerate() {
            assert_close(*got, *want, LIBM_WIDE, &format!("mlp_forward[{i}][{k}]"));
        }
    }
}

#[test]
fn jax_core_learned_field_substrate() {
    let fixture = load_fixture();
    for (i, case) in fixture["learned_field_substrate"]
        .as_array()
        .unwrap()
        .iter()
        .enumerate()
    {
        let inp = &case["inputs"];
        let exp = &case["outputs"];
        let layers = parse_layers(&inp["weights"]);
        let act = parse_activation(&inp["activation"]);
        let (chit, gamma) = learned_field_substrate(
            f(&inp["chit"]),
            f(&inp["gamma_ab"]),
            f(&inp["tau_obs"]),
            f(&inp["tau_obs_ref"]),
            &layers,
            act,
        );
        assert_close(
            chit,
            f(&exp["chit"]),
            LIBM_WIDE,
            &format!("learned_field_substrate[{i}].chit"),
        );
        assert_close(
            gamma,
            f(&exp["gamma_ab"]),
            LIBM_WIDE,
            &format!("learned_field_substrate[{i}].gamma_ab"),
        );
    }
}

#[test]
fn jax_core_laplace_log_evidence() {
    let fixture = load_fixture();
    for (i, case) in fixture["laplace_log_evidence"]
        .as_array()
        .unwrap()
        .iter()
        .enumerate()
    {
        let inp = &case["inputs"];
        let exp = &case["outputs"];
        let rows = mat_f(&inp["hessian"]);
        let h: [[f64; 2]; 2] = [[rows[0][0], rows[0][1]], [rows[1][0], rows[1][1]]];
        let n_obs = inp["n_obs"].as_u64().expect("n_obs u64") as usize;
        let ev = laplace_log_evidence(
            f(&inp["residual_at_map"]),
            &h,
            f(&inp["noise_variance"]),
            n_obs,
        );
        assert_close(
            ev,
            f(&exp["log_evidence"]),
            LIBM_WIDE,
            &format!("laplace_log_evidence[{i}]"),
        );
    }
}
